"""Program catalog for the Lunenburg FY28 model.

Every entry is a discrete, nameable thing a voter can reason about ("Grade 5 Band",
"2.0 Classroom Teachers at Turkey Hill"), with a cost anchored to a published source
wherever one exists.

source codes:
  ADD   = Budget Addendum: Multi-Scenario Financial Analysis, 3/13/26
  LINE  = FY27 line-item budget (sources/data/lps-budget-lines.csv)
  ATRP  = Additional Town Revenue Spending Plan (Sept 2026 STM)
  PR    = Town Manager press release, 4/17/26
  EST   = extrapolated by us -- NOT published by the district
"""

# tier: order the district itself sacrificed things (1 = given up first).
#   Derived from the Restoration -> Core -> Level Service -> Balanced deltas.
# status in FY27 adopted budget: 'cut' already gone, 'funded' still in, 'restoring'
#   pending the 9/3/26 Special Town Meeting.

CATEGORIES = {
    'core_classroom':   dict(label='Core Classroom & Class Size', color='blue'),
    'literacy':         dict(label='Early Literacy & Intervention', color='violet'),
    'sped':             dict(label='Special Education', color='teal'),
    'wellness':         dict(label='Student Mental Health & Health', color='green'),
    'advanced':         dict(label='Advanced & Elective Academics', color='indigo'),
    'arts':             dict(label='Arts & Music', color='pink'),
    'athletics':        dict(label='Athletics', color='orange'),
    'activities':       dict(label='Clubs & Activities', color='amber'),
    'leadership':       dict(label='School Leadership & Admin', color='slate'),
    'operations':       dict(label='Operations & Facilities', color='stone'),
    'technology':       dict(label='Technology', color='cyan'),
}

# mandate: 'legal' cannot be cut without violating state/federal law or a court order;
#          'contract' bound by collective bargaining for the budget year;
#          'discretionary' the School Committee can cut it by vote.
PROGRAMS = [
 # ---- already cut to reach the adopted FY27 Balanced budget -------------------
 dict(id='es_teachers_2fte', name='2.0 Classroom Teachers — Turkey Hill (gr 3-5)',
      cat='core_classroom', cost=171811, fte=2.0, mandate='discretionary',
      status='cut', tier=9, source='ADD',
      impact='Class sizes at Turkey Hill rise toward 27-30 students.'),
 dict(id='ps_teachers_2fte', name='2.0 Classroom Teachers — Primary (gr 1-2)',
      cat='core_classroom', cost=205019, fte=2.0, mandate='discretionary',
      status='cut', tier=9, source='ADD',
      impact='Class sizes at the Primary School rise toward 27-30 students.'),
 dict(id='interventionist_ps', name='1.0 Interventionist — Primary',
      cat='literacy', cost=135930, fte=1.0, mandate='discretionary',
      status='cut', tier=6, source='ADD',
      impact='Small-group reading and math intervention capacity cut at K-2.'),
 dict(id='interventionist_thes', name='0.5 Interventionist — Turkey Hill',
      cat='literacy', cost=53674, fte=0.5, mandate='discretionary',
      status='cut', tier=6, source='ADD',
      impact='Halves targeted intervention for grades 3-5.'),
 dict(id='asst_principal', name='1.0 Assistant Principal (attrition)',
      cat='leadership', cost=152829, fte=1.0, mandate='discretionary',
      status='cut', tier=7, source='ADD',
      impact='Primary and Turkey Hill now share a single Assistant Principal.'),
 dict(id='cota', name='1.0 Certified Occupational Therapy Assistant (attrition)',
      cat='sped', cost=74147, fte=1.0, mandate='discretionary',
      status='cut', tier=5, source='ADD',
      impact='Occupational Therapist absorbs a higher caseload.'),
 dict(id='custodian', name='1.0 Custodian — High School (attrition)',
      cat='operations', cost=48630, fte=1.0, mandate='discretionary',
      status='cut', tier=4, source='ADD',
      impact='Daily upkeep of the high school handled by a smaller team.'),
 dict(id='music_thes_02', name='0.2 Music Teacher — Turkey Hill',
      cat='arts', cost=14488, fte=0.2, mandate='discretionary',
      status='cut', tier=2, source='ADD',
      impact='Eliminates Grade 5 Band; larger arts class sizes.'),
 dict(id='athletic_transport', name='All Athletic Transportation',
      cat='athletics', cost=127550, fte=0, mandate='discretionary',
      status='cut', tier=1, source='LINE',
      impact='Families must drive athletes to every away contest.'),
 dict(id='athletic_coaches_partial', name='Athletic Coaching Stipends (partial)',
      cat='athletics', cost=72113, fte=0, mandate='discretionary',
      status='cut', tier=1, source='LINE',
      impact='Reduced coaching across the varsity program.'),
 dict(id='athletic_trainer_half', name='0.5 Athletic Trainer',
      cat='athletics', cost=34258, fte=0.5, mandate='discretionary',
      status='cut', tier=1, source='LINE',
      impact='Certified trainer coverage halved at practices and games.'),
 dict(id='ms_freshman_coaches', name='Middle School & Freshman Sports',
      cat='athletics', cost=14415, fte=0, mandate='discretionary',
      status='cut', tier=1, source='ADD',
      impact='No school-sponsored sports below the varsity level.'),
 dict(id='curriculum_adoption', name='Curriculum Adoption Cycle',
      cat='core_classroom', cost=40408, fte=0, mandate='discretionary',
      status='cut', tier=3, source='LINE',
      impact='Textbooks and core materials age another year without replacement.'),
 dict(id='band_transport', name='Band & Music Transportation',
      cat='arts', cost=5000, fte=0, mandate='discretionary',
      status='cut', tier=1, source='LINE',
      impact='No district transport to festivals, competitions, or performances.'),
 dict(id='custodial_supplies', name='Custodial Supplies (reduction)',
      cat='operations', cost=15000, fte=0, mandate='discretionary',
      status='cut', tier=3, source='LINE', impact='Reduced cleaning supply stock.'),
 dict(id='ms_custodian_partial', name='Middle School Custodial Hours',
      cat='operations', cost=9661, fte=0, mandate='discretionary',
      status='cut', tier=4, source='LINE', impact='Reduced custodial coverage at LMS.'),

 # ---- being restored at the 9/3/26 Special Town Meeting ----------------------
 dict(id='reading_spec_ps', name='1.0 Reading Specialist — Primary',
      cat='literacy', cost=103722, fte=1.0, mandate='discretionary',
      status='restoring', tier=6, source='ATRP',
      impact='Tier 2/3 phonics intervention for K-2. One-time funded in FY27.'),
 dict(id='reading_spec_thes', name='1.0 Reading Specialist — Turkey Hill',
      cat='literacy', cost=103722, fte=1.0, mandate='discretionary',
      status='restoring', tier=6, source='ATRP',
      impact='Addresses the "fourth-grade slump" in grades 3-5. One-time funded.'),
 dict(id='lhs_ap_half', name='0.5 -> 1.0 Assistant Principal — High School',
      cat='leadership', cost=90450, fte=0.5, mandate='discretionary',
      status='restoring', tier=7, source='ATRP',
      impact='Full-time AP for discipline, climate, and staff support. One-time funded.'),
 dict(id='ignite_seats', name='52 Ignite Tutoring Seats — Primary',
      cat='literacy', cost=129458, fte=0, mandate='discretionary',
      status='restoring', tier=6, source='ATRP',
      impact='1:1 high-dosage reading tutoring for 52 K-2 students. One-time funded.'),
 dict(id='music_lhs_04', name='0.6 -> 1.0 Music Teacher — High School',
      cat='arts', cost=26370, fte=0.4, mandate='discretionary',
      status='restoring', tier=2, source='ATRP',
      impact='New music electives; frees a PE section for seniors. One-time funded.'),

 # ---- the district asked for these and did not get them ---------------------
 dict(id='bridge_teacher', name='1.0 Bridge Program Teacher — LHS',
      cat='wellness', cost=107347, fte=1.0, mandate='discretionary',
      status='unfunded', tier=8, source='ADD',
      impact='Would restore transitional support for students in crisis.'),
 dict(id='bridge_para', name='1.0 Bridge Paraprofessional — LHS',
      cat='wellness', cost=57111, fte=1.0, mandate='discretionary',
      status='unfunded', tier=8, source='ADD', impact='Staffs the Bridge program.'),
 dict(id='para_k', name='1.0 Paraprofessional — Kindergarten',
      cat='core_classroom', cost=57111, fte=1.0, mandate='discretionary',
      status='unfunded', tier=9, source='ADD',
      impact='Adult support in kindergarten rooms approaching 30 students.'),
 dict(id='interventionist_lms', name='1.0 Interventionist — Middle School',
      cat='literacy', cost=107347, fte=1.0, mandate='discretionary',
      status='unfunded', tier=6, source='ADD',
      impact='Only tier restored under a Tier 2 override.'),
 dict(id='world_language_lhs', name='1.0 World Language Teacher — LHS',
      cat='advanced', cost=107347, fte=1.0, mandate='discretionary',
      status='unfunded', tier=10, source='ADD',
      impact='Preserves Latin, Spanish and French offerings.'),
 dict(id='ell_teacher', name='1.0 English Language Learning Teacher',
      cat='sped', cost=107347, fte=1.0, mandate='legal',
      status='unfunded', tier=12, source='ADD',
      impact='Legally required services for multilingual learners.'),
 dict(id='asst_business_mgr', name='1.0 Assistant Business Manager',
      cat='leadership', cost=10000, fte=1.0, mandate='discretionary',
      status='unfunded', tier=11, source='ADD',
      impact='State reporting compliance; avoids financial penalties.'),
 dict(id='state_reporting_sec', name='0.5 State Reporting Secretary',
      cat='leadership', cost=31000, fte=0.5, mandate='discretionary',
      status='unfunded', tier=11, source='ADD',
      impact='DESE reporting compliance.'),
 dict(id='interventionist_lhs', name='1.0 Interventionist — High School',
      cat='literacy', cost=161064, fte=1.0, mandate='discretionary',
      status='unfunded', tier=6, source='ADD',
      impact='First position sacrificed when Restoration steps down to Core.'),

 # ---- still funded today; these are what future deficits would reach --------
 dict(id='athletics_remaining', name='Remaining Athletics Program (all sports)',
      cat='athletics', cost=217908, fte=1.5, mandate='discretionary',
      status='funded', tier=1, source='LINE',
      impact='Ends all school-sponsored sports: coaches, trainer, AD, officials, equipment.'),
 dict(id='hs_advisors', name='High School Clubs & After-School Advisors',
      cat='activities', cost=11731, fte=0, mandate='discretionary',
      status='funded', tier=1, source='LINE',
      impact='Ends every advised club at the high school.'),
 dict(id='art_supplies', name='Art Supplies — all four schools',
      cat='arts', cost=30685, fte=0, mandate='discretionary',
      status='funded', tier=2, source='LINE',
      impact='Art classes run without consumable materials.'),
 dict(id='music_supplies', name='Band & Music Supplies, Equipment, Repair',
      cat='arts', cost=17073, fte=0, mandate='discretionary',
      status='funded', tier=2, source='LINE',
      impact='Instruments go unrepaired; no sheet music or reeds.'),
 dict(id='hs_dept_heads', name='High School Department Head Stipends',
      cat='leadership', cost=29950, fte=0, mandate='discretionary',
      status='funded', tier=3, source='LINE',
      impact='No curriculum leadership by subject at LHS.'),
 dict(id='prof_dev', name='Professional Development — district-wide',
      cat='core_classroom', cost=41800, fte=0, mandate='discretionary',
      status='funded', tier=3, source='LINE',
      impact='No training on new curriculum, literacy practice, or student mental health.'),
 dict(id='libraries', name='Library Staff & Materials — all four schools',
      cat='advanced', cost=221546, fte=4.0, mandate='discretionary',
      status='funded', tier=5, source='LINE',
      impact='Closes staffed libraries district-wide.'),
 dict(id='instr_materials', name='Classroom Instructional Materials & Workbooks',
      cat='core_classroom', cost=120677, fte=0, mandate='discretionary',
      status='funded', tier=4, source='LINE',
      impact='Teachers buy their own consumables or go without.'),
 dict(id='hs_electives_ap', name='Advanced Placement & Upper-Level Electives',
      cat='advanced', cost=290000, fte=2.8, mandate='discretionary',
      status='funded', tier=10, source='EST',
      impact='Collapses the AP course catalog; students lose college-credit pathways.'),
 dict(id='hs_music_program', name='High School Band & Chorus Program',
      cat='arts', cost=72440, fte=1.0, mandate='discretionary',
      status='funded', tier=2, source='EST',
      impact='Ends band and chorus at Lunenburg High School.'),
 dict(id='ms_electives', name='Middle School Exploratory & Elective Block',
      cat='advanced', cost=185000, fte=2.0, mandate='discretionary',
      status='funded', tier=10, source='EST',
      impact='Middle school reduced to core academics only.'),
 dict(id='guidance_partial', name='Guidance Counselors (1.0 reduction)',
      cat='wellness', cost=110000, fte=1.0, mandate='discretionary',
      status='funded', tier=13, source='EST',
      impact='Caseloads rise above 300:1; college counseling curtailed.'),
 dict(id='social_workers', name='Social Workers (1.0 reduction)',
      cat='wellness', cost=99007, fte=1.0, mandate='discretionary',
      status='funded', tier=13, source='EST',
      impact='A school loses its full-time mental-health clinician.'),
 dict(id='nurses_partial', name='School Nurse (1.0 reduction)',
      cat='wellness', cost=87870, fte=1.0, mandate='legal',
      status='funded', tier=15, source='EST',
      impact='Buildings share nursing coverage; medication administration at risk.'),
 dict(id='core_teachers_more', name='Additional Classroom Teachers (each 1.0)',
      cat='core_classroom', cost=102510, fte=1.0, mandate='contract',
      status='funded', tier=14, source='EST', repeatable=6,
      impact='Every further cut pushes average class size up by roughly one student.'),
 dict(id='sped_beyond_mandate', name='Special Education Above Legal Minimum',
      cat='sped', cost=180000, fte=2.0, mandate='legal',
      status='funded', tier=16, source='EST',
      impact='Would invite state findings and compensatory-services liability.'),

 # ---- operations & technology still funded (cuttable before academics) ------
 dict(id='device_refresh', name='Student Device Refresh & Computer Leases',
      cat='technology', cost=265316, fte=0, mandate='discretionary',
      status='funded', tier=3, source='LINE',
      impact='Chromebook replacement cycle stops; devices age past repair.'),
 dict(id='network_services', name='Network & Telecommunications Contracts',
      cat='technology', cost=55230, fte=0, mandate='discretionary',
      status='funded', tier=6, source='LINE',
      impact='Reduced bandwidth and support; state testing capacity at risk.'),
 dict(id='instr_tech', name='Instructional Technology Contracts (per school)',
      cat='technology', cost=87924, fte=0, mandate='discretionary',
      status='funded', tier=5, source='LINE',
      impact='Loses licensed classroom software and platforms.'),
 dict(id='building_maint', name='Building Maintenance Contracted Services',
      cat='operations', cost=257000, fte=0, mandate='discretionary',
      status='funded', tier=4, source='LINE',
      impact='Deferred maintenance accumulates; small failures become capital projects.'),
 dict(id='grounds_maint', name='Grounds Maintenance & Supplies',
      cat='operations', cost=79458, fte=0, mandate='discretionary',
      status='funded', tier=2, source='LINE',
      impact='Fields and grounds degrade; athletic surfaces become unsafe.'),
 dict(id='equipment_replace', name='Equipment Replacement & Capital Maintenance',
      cat='operations', cost=75045, fte=0, mandate='discretionary',
      status='funded', tier=3, source='LINE',
      impact='Boilers, kitchen and classroom equipment run to failure.'),
 dict(id='custodial_more', name='Custodial Staff (each further 1.0)',
      cat='operations', cost=48630, fte=1.0, mandate='contract',
      status='funded', tier=7, source='LINE', repeatable=3,
      impact='Cleaning frequency drops below health-code comfort in some buildings.'),
 dict(id='substitutes', name='Substitute Teacher Budget (reduction)',
      cat='core_classroom', cost=74500, fte=0, mandate='discretionary',
      status='funded', tier=8, source='LINE',
      impact='Classes combined or supervised by non-teachers when staff are absent.'),
 dict(id='sped_paras_more', name='Special Education Paraprofessionals (each 1.0)',
      cat='sped', cost=57111, fte=1.0, mandate='legal',
      status='funded', tier=14, source='LINE', repeatable=3,
      impact='IEP-mandated 1:1 and small-group support; cutting invites state findings.'),
]
