import { useMemo, useState } from 'react'
import raw from '../data/sources.json'

/** Every document this analysis is built on, listed.
 *
 *  The site asks a reader to accept a lot of arithmetic about their own tax bill. The
 *  honest answer to "says who?" is not a paragraph claiming the sources are public — it is
 *  the list, with the weak entries left in. So the two slide decks that turned out to be
 *  unreadable are here, the expired DESE contract templates are here, and the enterprise
 *  funds that have nothing to do with schools are here, each saying so.
 *
 *  Generated by scripts/build_source_index.py, which fails the build if a catalogued file
 *  is missing or an uncatalogued one appears. A source index that quietly drifts out of
 *  step with the archive is worse than none, because it is still believed.
 *
 *  Grouped rather than alphabetical: nobody wants "every document", they want the budget
 *  documents, or the contracts, or the thing that proves the override failed. Within a
 *  group the load-bearing documents come first — the ones a conclusion actually rests on —
 *  because a reader checking our work should meet those before the ones kept for
 *  completeness. */

type Item = {
  path: string; title: string; stars: number; what: string; kind: string
  bytes: number; url: string; count?: number; unit?: string
  textUrl?: string; offsite?: boolean
}
type Group = { id: string; title: string; blurb: string; origin: string; items: Item[] }
type Origin = { id: string; name: string; url: string | null }
type Board = { name: string; documents: number }

const S = raw as unknown as {
  generated: string; commit: string | null; origins: Origin[]; groups: Group[]
  corpusIndexUrl: string
  corpus: {
    boards: Board[]; boardCount: number; listed: number; fetched: number
    agendas: number; minutes: number; from: string | null; to: string | null
    textFiles: number; note: string; rebuild: string
  } | null
  totals: { documents: number; groups: number; bytes: number; loadBearing: number }
  note: string
}

const size = (b: number) =>
  b >= 1e6 ? `${(b / 1e6).toFixed(1)} MB` : `${Math.max(1, Math.round(b / 1e3))} KB`

/** Weight is stated in words, never by colour or a row of stars alone — the whole point
 *  of the label is that somebody deciding what to read can act on it. */
const WEIGHT: Record<number, { word: string; glyph: string; color: string }> = {
  3: { word: 'Load-bearing', glyph: '●', color: 'var(--brand)' },
  2: { word: 'Corroborating', glyph: '◐', color: 'var(--text-secondary)' },
  1: { word: 'Context', glyph: '○', color: 'var(--text-muted)' },
}

function Row({ it }: { it: Item }) {
  const w = WEIGHT[it.stars] ?? WEIGHT[1]
  return (
    <li className="py-3.5 border-t" style={{ borderColor: 'var(--grid)' }}>
      <div className="flex flex-wrap items-baseline gap-x-2.5 gap-y-1">
        {/* The title is the download. Nothing here is a preview or a summary of a
            document held somewhere else — this is the file, exactly as it was
            published. */}
        <a href={it.url} download
          {...(it.offsite ? { target: '_blank', rel: 'noopener noreferrer' } : {})}
          className="text-[14px] font-semibold leading-snug underline
          decoration-1 underline-offset-2" style={{ color: 'var(--series-cost)' }}>
          {it.title}
        </a>
        <span className="inline-flex items-center gap-1 text-[10.5px] font-semibold
          uppercase tracking-wider whitespace-nowrap" style={{ color: w.color }}>
          <span aria-hidden="true">{w.glyph}</span>{w.word}
        </span>
      </div>
      <p className="mt-1 text-[13px] leading-relaxed max-w-3xl"
        style={{ color: 'var(--text-secondary)' }}>{it.what}</p>
      <p className="mt-1.5 text-[11.5px] tnum flex flex-wrap gap-x-2.5 gap-y-0.5"
        style={{ color: 'var(--text-muted)' }}>
        <span>{it.kind}</span>
        <span aria-hidden="true">&middot;</span>
        <span>{size(it.bytes)}</span>
        {it.count != null && (<>
          <span aria-hidden="true">&middot;</span>
          <span>{it.count.toLocaleString()} {it.unit}</span>
        </>)}
        {it.textUrl && (<>
          <span aria-hidden="true">&middot;</span>
          <a href={it.textUrl} download className="underline"
            style={{ color: 'var(--text-secondary)' }}>extracted text</a>
        </>)}
        <span aria-hidden="true">&middot;</span>
        <code style={{ color: 'var(--text-muted)' }}>sources/{it.path}</code>
      </p>
      {it.offsite && (
        <p className="mt-1 text-[11.5px]" style={{ color: 'var(--text-muted)' }}>
          Served from separate storage because it is too large for this site&rsquo;s host.
          Same file, unaltered — a page scan we have not re-encoded, because a source
          document changed to fit a web host is no longer the source document. The
          extracted text beside it is a great deal smaller.
        </p>
      )}
    </li>
  )
}

export function SourceIndex() {
  const [q, setQ] = useState('')
  const [open, setOpen] = useState<string | null>(S.groups[0]?.id ?? null)

  const needle = q.trim().toLowerCase()
  const origin = useMemo(
    () => Object.fromEntries(S.origins.map(o => [o.id, o])) as Record<string, Origin>, [])

  // Searching collapses the grouping on purpose: somebody typing "circuit breaker" wants
  // the document, not the category it happens to live in.
  const groups = useMemo(() => {
    if (!needle) return S.groups
    return S.groups
      .map(g => ({
        ...g,
        items: g.items.filter(i =>
          (i.title + i.what + i.path + i.kind).toLowerCase().includes(needle)),
      }))
      .filter(g => g.items.length)
  }, [needle])

  const hits = groups.reduce((n, g) => n + g.items.length, 0)

  return (
    <div>
      {/* ---------- what is in here ---------- */}
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 mb-6">
        <div className="card p-4">
          <p className="text-[11px] font-semibold uppercase tracking-widest mb-1.5"
            style={{ color: 'var(--text-muted)' }}>Documents</p>
          <p className="text-2xl font-bold tnum leading-none">{S.totals.documents}</p>
          <p className="text-xs mt-1.5" style={{ color: 'var(--text-secondary)' }}>
            in {S.totals.groups} groups, {(S.totals.bytes / 1e6).toFixed(0)} MB
          </p>
        </div>
        <div className="card p-4">
          <p className="text-[11px] font-semibold uppercase tracking-widest mb-1.5"
            style={{ color: 'var(--text-muted)' }}>Load-bearing</p>
          <p className="text-2xl font-bold tnum leading-none" style={{ color: 'var(--brand)' }}>
            {S.totals.loadBearing}</p>
          <p className="text-xs mt-1.5" style={{ color: 'var(--text-secondary)' }}>
            A conclusion on this site rests on each of these
          </p>
        </div>
        <div className="card p-4">
          <p className="text-[11px] font-semibold uppercase tracking-widest mb-1.5"
            style={{ color: 'var(--text-muted)' }}>Meeting archive</p>
          <p className="text-2xl font-bold tnum leading-none">
            {S.corpus ? S.corpus.fetched.toLocaleString() : '—'}</p>
          <p className="text-xs mt-1.5" style={{ color: 'var(--text-secondary)' }}>
            {S.corpus ? `agendas and minutes across ${S.corpus.boardCount} boards` : ''}
          </p>
        </div>
        <div className="card p-4">
          <p className="text-[11px] font-semibold uppercase tracking-widest mb-1.5"
            style={{ color: 'var(--text-muted)' }}>Behind a paywall</p>
          <p className="text-2xl font-bold tnum leading-none"
            style={{ color: 'var(--status-good)' }}>0</p>
          <p className="text-xs mt-1.5" style={{ color: 'var(--text-secondary)' }}>
            All of it is published. None of it was obtained by request
          </p>
        </div>
      </div>

      {/* ---------- search ---------- */}
      <div className="flex flex-wrap items-center gap-3 mb-4">
        <input
          type="search" value={q} onChange={e => setQ(e.target.value)}
          placeholder="Search the documents — try &ldquo;circuit breaker&rdquo; or &ldquo;override&rdquo;"
          aria-label="Search the source documents"
          className="flex-1 min-w-[240px] rounded-md px-3 py-2 text-[13px] border"
          style={{ borderColor: 'var(--grid)', background: 'var(--surface-1)',
                   color: 'var(--text-primary)' }} />
        {needle && (
          <p className="text-xs tnum" style={{ color: 'var(--text-secondary)' }}>
            {hits} of {S.totals.documents}
            <button onClick={() => setQ('')} className="ml-2 underline"
              style={{ color: 'var(--brand)' }}>clear</button>
          </p>
        )}
      </div>

      {/* ---------- the groups ---------- */}
      <div className="flex flex-col gap-2.5">
        {groups.map(g => {
          const o = origin[g.origin]
          const isOpen = !!needle || open === g.id
          return (
            <div key={g.id} className="card overflow-hidden">
              <button
                onClick={() => setOpen(open === g.id ? null : g.id)}
                aria-expanded={isOpen}
                className="w-full text-left px-5 py-4 flex items-start justify-between gap-4">
                <span className="min-w-0">
                  <span className="flex flex-wrap items-baseline gap-x-2.5">
                    <span className="text-[15px] font-bold">{g.title}</span>
                    <span className="text-[11.5px] tnum" style={{ color: 'var(--text-muted)' }}>
                      {g.items.length} {g.items.length === 1 ? 'document' : 'documents'}
                    </span>
                  </span>
                  <span className="block mt-1 text-[13px] leading-relaxed max-w-3xl"
                    style={{ color: 'var(--text-secondary)' }}>{g.blurb}</span>
                </span>
                {!needle && (
                  <span aria-hidden="true" className="text-lg leading-none mt-0.5 shrink-0"
                    style={{ color: 'var(--text-muted)' }}>{isOpen ? '−' : '+'}</span>
                )}
              </button>
              {isOpen && (
                <div className="px-5 pb-4">
                  {o?.url && (
                    <p className="text-[12px] mb-1" style={{ color: 'var(--text-muted)' }}>
                      Published by{' '}
                      <a href={o.url} target="_blank" rel="noopener noreferrer"
                        style={{ color: 'var(--brand)' }}>{o.name}</a>
                    </p>
                  )}
                  {o && !o.url && (
                    <p className="text-[12px] mb-1" style={{ color: 'var(--text-muted)' }}>
                      {o.name}
                    </p>
                  )}
                  <ul>{g.items.map(it => <Row key={it.path} it={it} />)}</ul>
                </div>
              )}
            </div>
          )
        })}
        {!groups.length && (
          <p className="text-[13px] py-6" style={{ color: 'var(--text-secondary)' }}>
            Nothing matches &ldquo;{q}&rdquo;. The archive is 64 documents plus the meeting
            minutes &mdash; try a broader word.
          </p>
        )}
      </div>

      {/* ---------- the meeting archive ---------- */}
      {S.corpus && !needle && (
        <div className="card p-5 mt-2.5">
          <h3 className="text-[15px] font-bold">The meeting archive</h3>
          <p className="mt-1 text-[13px] leading-relaxed max-w-3xl"
            style={{ color: 'var(--text-secondary)' }}>{S.corpus.note}</p>
          <p className="mt-2 text-[13px]">
            <a href={S.corpusIndexUrl} download className="font-semibold underline"
              style={{ color: 'var(--series-cost)' }}>
              Download the archive index (CSV) &rarr;
            </a>
            <span className="ml-2" style={{ color: 'var(--text-muted)' }}>
              board, date, kind, and the town&rsquo;s own URL for every one of them
            </span>
          </p>
          <p className="mt-2 text-[12px] tnum" style={{ color: 'var(--text-muted)' }}>
            {S.corpus.listed.toLocaleString()} documents listed by the town &middot;{' '}
            {S.corpus.fetched.toLocaleString()} retrieved &middot; {S.corpus.agendas} agendas
            and {S.corpus.minutes} sets of minutes &middot; {S.corpus.from} to {S.corpus.to}
          </p>
          <div className="mt-4 overflow-x-auto">
            <table className="w-full text-[12.5px]">
              <caption className="sr-only">Documents held per town board</caption>
              <thead>
                <tr style={{ color: 'var(--text-muted)' }}>
                  <th className="text-left font-semibold pb-1.5">Board</th>
                  <th className="text-right font-semibold pb-1.5">Documents</th>
                </tr>
              </thead>
              <tbody>
                {S.corpus.boards.slice(0, 12).map(b => (
                  <tr key={b.name} className="border-t" style={{ borderColor: 'var(--grid)' }}>
                    <td className="py-1.5">{b.name}</td>
                    <td className="py-1.5 text-right tnum">{b.documents}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          {S.corpus.boards.length > 12 && (
            <p className="mt-2 text-[12px]" style={{ color: 'var(--text-muted)' }}>
              and {S.corpus.boards.length - 12} more boards, down to committees that met
              twice.
            </p>
          )}
        </div>
      )}

      <p className="text-xs leading-relaxed mt-5 max-w-3xl" style={{ color: 'var(--text-muted)' }}>
        {S.note} Index generated {S.generated}
        {S.commit ? ` from commit ${S.commit}` : ''}.
      </p>
    </div>
  )
}
