import { useMemo, useState } from 'react'
import Papa from 'papaparse'
import raw from '../data/sources.json'

/** Every document this analysis is built on, listed.
 *
 *  The site asks a reader to accept a lot of arithmetic about their own tax bill. The
 *  honest answer to "says who?" is not a paragraph claiming the sources are public — it is
 *  the list, with the weak entries left in. So the two slide decks that turned out to be
 *  unreadable are here, the expired DESE contract templates are here, and the enterprise
 *  funds that have nothing to do with schools are here, each saying so.
 *
 *  Generated by scripts/build_source_index.py, which fails the build if a catalogued file
 *  is missing or an uncatalogued one appears. A source index that quietly drifts out of
 *  step with the archive is worse than none, because it is still believed.
 *
 *  Grouped rather than alphabetical: nobody wants "every document", they want the budget
 *  documents, or the contracts, or the thing that proves the override failed. Within a
 *  group the load-bearing documents come first — the ones a conclusion actually rests on —
 *  because a reader checking our work should meet those before the ones kept for
 *  completeness. */

type Item = {
  path: string; title: string; stars: number; what: string; kind: string
  bytes: number; url: string; count?: number; unit?: string
  textUrl?: string; offsite?: boolean; byRequest?: boolean
}
type Group = { id: string; section?: string; title: string; blurb: string
               origin: string; items: Item[] }
type Section = { title: string; blurb: string }
type Origin = { id: string; name: string; url: string | null }
type Board = { name: string; documents: number }

const S = raw as unknown as {
  generated: string; origins: Origin[]; groups: Group[]
  sections: Record<string, Section>
  corpusIndexUrl: string
  corpus: {
    boards: Board[]; boardCount: number; listed: number; fetched: number
    agendas: number; minutes: number; from: string | null; to: string | null
    textFiles: number; note: string; rebuild: string
  } | null
  totals: { documents: number; groups: number; bytes: number; loadBearing: number }
  note: string
}

const size = (b: number) =>
  b >= 1e6 ? `${(b / 1e6).toFixed(1)} MB` : `${Math.max(1, Math.round(b / 1e3))} KB`

/** Weight is stated in words, never by colour or a row of stars alone — the whole point
 *  of the label is that somebody deciding what to read can act on it. */
const WEIGHT: Record<number, { word: string; glyph: string; color: string }> = {
  3: { word: 'Load-bearing', glyph: '●', color: 'var(--brand)' },
  2: { word: 'Corroborating', glyph: '◐', color: 'var(--text-secondary)' },
  1: { word: 'Context', glyph: '○', color: 'var(--text-muted)' },
}

function Row({ it }: { it: Item }) {
  const w = WEIGHT[it.stars] ?? WEIGHT[1]
  return (
    <li className="py-3.5 border-t" style={{ borderColor: 'var(--grid)' }}>
      <div className="flex flex-wrap items-baseline gap-x-2.5 gap-y-1">
        {/* The title is the download. Nothing here is a preview or a summary of a
            document held somewhere else — this is the file, exactly as it was
            published. */}
        <a href={it.url} download
          {...(it.offsite ? { target: '_blank', rel: 'noopener noreferrer' } : {})}
          className="text-[14px] font-semibold leading-snug underline
          decoration-1 underline-offset-2" style={{ color: 'var(--series-cost)' }}>
          {it.title}
        </a>
        <span className="inline-flex items-center gap-1 text-[10.5px] font-semibold
          uppercase tracking-wider whitespace-nowrap" style={{ color: w.color }}>
          <span aria-hidden="true">{w.glyph}</span>{w.word}
        </span>
        {it.byRequest && (
          <span className="inline-flex items-center gap-1 text-[10.5px] font-semibold
            uppercase tracking-wider whitespace-nowrap"
            style={{ color: 'var(--status-warning)' }}
            title="Obtained from the Town by records request, not published online">
            <span aria-hidden="true">&#9993;</span>By request
          </span>
        )}
      </div>
      <p className="mt-1 text-[13px] leading-relaxed max-w-3xl"
        style={{ color: 'var(--text-secondary)' }}>{it.what}</p>
      <p className="mt-1.5 text-[11.5px] tnum flex flex-wrap gap-x-2.5 gap-y-0.5"
        style={{ color: 'var(--text-muted)' }}>
        <span>{it.kind}</span>
        <span aria-hidden="true">&middot;</span>
        <span>{size(it.bytes)}</span>
        {it.count != null && (<>
          <span aria-hidden="true">&middot;</span>
          <span>{it.count.toLocaleString()} {it.unit}</span>
        </>)}
        {it.textUrl && (<>
          <span aria-hidden="true">&middot;</span>
          <a href={it.textUrl} download className="underline"
            style={{ color: 'var(--text-secondary)' }}>extracted text</a>
        </>)}
        <span aria-hidden="true">&middot;</span>
        <code style={{ color: 'var(--text-muted)' }}>sources/{it.path}</code>
      </p>
      {it.offsite && (
        <p className="mt-1 text-[11.5px]" style={{ color: 'var(--text-muted)' }}>
          Served from separate storage because it is too large for this site&rsquo;s host.
          Same file, unaltered — a page scan we have not re-encoded, because a source
          document changed to fit a web host is no longer the source document. The
          extracted text beside it is a great deal smaller.
        </p>
      )}
    </li>
  )
}

export function SourceIndex() {
  const [q, setQ] = useState('')
  const [open, setOpen] = useState<string | null>(S.groups[0]?.id ?? null)

  const needle = q.trim().toLowerCase()
  const origin = useMemo(
    () => Object.fromEntries(S.origins.map(o => [o.id, o])) as Record<string, Origin>, [])

  // Searching collapses the grouping on purpose: somebody typing "circuit breaker" wants
  // the document, not the category it happens to live in.
  const groups = useMemo(() => {
    if (!needle) return S.groups
    return S.groups
      .map(g => ({
        ...g,
        items: g.items.filter(i =>
          (i.title + i.what + i.path + i.kind).toLowerCase().includes(needle)),
      }))
      .filter(g => g.items.length)
  }, [needle])

  const hits = groups.reduce((n, g) => n + g.items.length, 0)
  const byRequest = S.groups.reduce(
    (n, g) => n + g.items.filter(i => i.byRequest).length, 0)

  return (
    <div>
      {/* ---------- what is in here ---------- */}
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 mb-6">
        <div className="card p-4">
          <p className="text-[11px] font-semibold uppercase tracking-widest mb-1.5"
            style={{ color: 'var(--text-muted)' }}>Documents</p>
          <p className="text-2xl font-bold tnum leading-none">{S.totals.documents}</p>
          <p className="text-xs mt-1.5" style={{ color: 'var(--text-secondary)' }}>
            in {S.totals.groups} groups, {(S.totals.bytes / 1e6).toFixed(0)} MB
          </p>
        </div>
        <div className="card p-4">
          <p className="text-[11px] font-semibold uppercase tracking-widest mb-1.5"
            style={{ color: 'var(--text-muted)' }}>Load-bearing</p>
          <p className="text-2xl font-bold tnum leading-none" style={{ color: 'var(--brand)' }}>
            {S.totals.loadBearing}</p>
          <p className="text-xs mt-1.5" style={{ color: 'var(--text-secondary)' }}>
            A conclusion on this site rests on each of these
          </p>
        </div>
        <div className="card p-4">
          <p className="text-[11px] font-semibold uppercase tracking-widest mb-1.5"
            style={{ color: 'var(--text-muted)' }}>Meeting archive</p>
          <p className="text-2xl font-bold tnum leading-none">
            {S.corpus ? S.corpus.fetched.toLocaleString() : '—'}</p>
          <p className="text-xs mt-1.5" style={{ color: 'var(--text-secondary)' }}>
            {S.corpus ? `agendas and minutes across ${S.corpus.boardCount} boards` : ''}
          </p>
        </div>
        <div className="card p-4">
          <p className="text-[11px] font-semibold uppercase tracking-widest mb-1.5"
            style={{ color: 'var(--text-muted)' }}>By records request</p>
          <p className="text-2xl font-bold tnum leading-none"
            style={{ color: 'var(--status-warning)' }}>{byRequest}</p>
          <p className="text-xs mt-1.5" style={{ color: 'var(--text-secondary)' }}>
            The rest was already public. These had to be asked for &mdash; and they are the
            only ones recording money actually spent
          </p>
        </div>
      </div>

      {/* ---------- search ---------- */}
      <div className="flex flex-wrap items-center gap-3 mb-4">
        <input
          type="search" value={q} onChange={e => setQ(e.target.value)}
          placeholder="Search the documents — try &ldquo;circuit breaker&rdquo; or &ldquo;override&rdquo;"
          aria-label="Search the source documents"
          className="flex-1 min-w-[240px] rounded-md px-3 py-2 text-[13px] border"
          style={{ borderColor: 'var(--grid)', background: 'var(--surface-1)',
                   color: 'var(--text-primary)' }} />
        {needle && (
          <p className="text-xs tnum" style={{ color: 'var(--text-secondary)' }}>
            {hits} of {S.totals.documents}
            <button onClick={() => setQ('')} className="ml-2 underline"
              style={{ color: 'var(--brand)' }}>clear</button>
          </p>
        )}
      </div>

      {/* ---------- the groups ---------- */}
      <div className="flex flex-col gap-2.5">
        {groups.map((g, gi) => {
          const o = origin[g.origin]
          const isOpen = !!needle || open === g.id
          // The divide between what the town published and what we wrote is the most
          // important thing on this page — more important than any grouping inside either
          // half — so it gets a header rather than an ordering the reader has to infer.
          const sec = !needle && g.section && g.section !== groups[gi - 1]?.section
            ? S.sections[g.section] : null
          const ours = g.section === 'ours'
          return (
            <div key={`s-${g.id}`} className="contents">
            {/* Closes the town's half, before the line saying what follows is ours. */}
            {sec && g.section === 'ours' && !needle && <MeetingArchive />}
            {sec && (
              <div className={gi === 0 ? 'mb-1' : 'mt-8 mb-1 pt-7 border-t-2'}
                style={gi === 0 ? undefined : { borderColor: ours ? 'var(--status-warning)' : 'var(--grid)' }}>
                <p className="text-[11px] font-bold uppercase tracking-widest mb-1.5"
                  style={{ color: ours ? 'var(--status-warning)' : 'var(--text-muted)' }}>
                  {ours ? 'Not town information' : 'Primary documents'}
                </p>
                <h3 className="text-lg sm:text-xl font-bold tracking-tight mb-2">{sec.title}</h3>
                <p className="text-[13.5px] leading-relaxed max-w-3xl"
                  style={{ color: 'var(--text-secondary)' }}>{sec.blurb}</p>
              </div>
            )}
            <div className="card overflow-hidden">
              <button
                onClick={() => setOpen(open === g.id ? null : g.id)}
                aria-expanded={isOpen}
                className="w-full text-left px-5 py-4 flex items-start justify-between gap-4">
                <span className="min-w-0">
                  <span className="flex flex-wrap items-baseline gap-x-2.5">
                    <span className="text-[15px] font-bold">{g.title}</span>
                    <span className="text-[11.5px] tnum" style={{ color: 'var(--text-muted)' }}>
                      {g.items.length} {g.items.length === 1 ? 'document' : 'documents'}
                    </span>
                  </span>
                  <span className="block mt-1 text-[13px] leading-relaxed max-w-3xl"
                    style={{ color: 'var(--text-secondary)' }}>{g.blurb}</span>
                </span>
                {!needle && (
                  <span aria-hidden="true" className="text-lg leading-none mt-0.5 shrink-0"
                    style={{ color: 'var(--text-muted)' }}>{isOpen ? '−' : '+'}</span>
                )}
              </button>
              {isOpen && (
                <div className="px-5 pb-4">
                  {o?.url && (
                    <p className="text-[12px] mb-1" style={{ color: 'var(--text-muted)' }}>
                      Published by{' '}
                      <a href={o.url} target="_blank" rel="noopener noreferrer"
                        style={{ color: 'var(--brand)' }}>{o.name}</a>
                    </p>
                  )}
                  {o && !o.url && (
                    <p className="text-[12px] mb-1" style={{ color: 'var(--text-muted)' }}>
                      {o.name}
                    </p>
                  )}
                  <ul>{g.items.map(it => <Row key={it.path} it={it} />)}</ul>
                </div>
              )}
            </div>
            </div>
          )
        })}
        {!groups.length && (
          <p className="text-[13px] py-6" style={{ color: 'var(--text-secondary)' }}>
            Nothing matches &ldquo;{q}&rdquo;. The archive is 64 documents plus the meeting
            minutes &mdash; try a broader word.
          </p>
        )}
      </div>

      <p className="text-xs leading-relaxed mt-5 max-w-3xl" style={{ color: 'var(--text-muted)' }}>
        {S.note} Index generated {S.generated}.
      </p>
    </div>
  )
}

/** The town's own agendas and minutes.
 *
 *  Rendered inside the town's half of the archive rather than after everything, where it
 *  sat beneath a heading announcing that what followed was written by us. Of all the
 *  things this page could mislead a reader about, who wrote a document is the one it
 *  exists to get right. */
type Row = { board: string; date: string; kind: string; file_id: string
             path: string; url: string }

function MeetingArchive() {
  const [board, setBoard] = useState<string | null>(null)
  const [rows, setRows] = useState<Row[] | null>(null)
  const [failed, setFailed] = useState(false)

  /* 1,383 rows are too many to ship in the bundle for a panel most readers never open, and
     the index is already published as a download. So it is fetched once, on the first
     expand, from the same file the download button hands over. */
  const load = async () => {
    if (rows || failed) return
    try {
      const text = await fetch(S.corpusIndexUrl).then(r => {
        if (!r.ok) throw new Error(String(r.status))
        return r.text()
      })
      const parsed = Papa.parse<Row>(text, { header: true, skipEmptyLines: true })
      setRows(parsed.data.filter(r => r.board))
    } catch {
      setFailed(true)
    }
  }

  if (!S.corpus) return null
  return (
        <div className="card p-5 mb-9">
          <h3 className="text-[15px] font-bold">The meeting archive</h3>
          <p className="mt-1 text-[13px] leading-relaxed max-w-3xl"
            style={{ color: 'var(--text-secondary)' }}>{S.corpus.note}</p>
          <p className="mt-2 text-[13px]">
            <a href={S.corpusIndexUrl} download className="font-semibold underline"
              style={{ color: 'var(--series-cost)' }}>
              Download the archive index (CSV) &rarr;
            </a>
            <span className="ml-2" style={{ color: 'var(--text-muted)' }}>
              board, date, kind, and the town&rsquo;s own URL for every one of them
            </span>
          </p>
          <p className="mt-2 text-[12px] tnum" style={{ color: 'var(--text-muted)' }}>
            {S.corpus.listed.toLocaleString()} documents listed by the town &middot;{' '}
            {S.corpus.fetched.toLocaleString()} retrieved &middot; {S.corpus.agendas} agendas
            and {S.corpus.minutes} sets of minutes &middot; {S.corpus.from} to {S.corpus.to}
          </p>
          <ul className="mt-4 flex flex-col">
            {S.corpus.boards.map(b => {
              const isOpen = board === b.name
              const docs = rows?.filter(r => r.board === b.name) ?? []
              return (
                <li key={b.name} className="border-t" style={{ borderColor: 'var(--grid)' }}>
                  <button
                    onClick={() => { setBoard(isOpen ? null : b.name); void load() }}
                    aria-expanded={isOpen}
                    className="w-full flex items-baseline justify-between gap-3 py-2 text-left">
                    <span className="text-[12.5px] flex items-baseline gap-2 min-w-0">
                      <span aria-hidden="true" className="shrink-0"
                        style={{ color: 'var(--text-muted)' }}>{isOpen ? '−' : '+'}</span>
                      <span className="truncate">{b.name}</span>
                    </span>
                    <span className="text-[12.5px] tnum shrink-0"
                      style={{ color: 'var(--text-muted)' }}>{b.documents}</span>
                  </button>

                  {isOpen && (
                    <div className="pb-3 pl-5">
                      {!rows && !failed && (
                        <p className="text-[12px]" style={{ color: 'var(--text-muted)' }}>
                          Loading the index&hellip;
                        </p>
                      )}
                      {failed && (
                        <p className="text-[12px]" style={{ color: 'var(--status-critical)' }}>
                          The index did not load. It is downloadable above.
                        </p>
                      )}
                      {rows && (
                        <ul className="flex flex-col gap-0.5">
                          {docs.map(d => (
                            <li key={d.file_id} className="text-[12px] flex gap-2.5">
                              <span className="tnum shrink-0 w-[5.5rem]"
                                style={{ color: 'var(--text-muted)' }}>{d.date}</span>
                              <span className="shrink-0 w-[4.2rem] capitalize"
                                style={{ color: 'var(--text-secondary)' }}>{d.kind}</span>
                              {/* Straight to the town's own copy. Ours are scans we did not
                                  commit; theirs is the authoritative one and it is free. */}
                              <a href={d.url} target="_blank" rel="noopener noreferrer"
                                className="underline min-w-0"
                                style={{ color: 'var(--series-cost)' }}>
                                {d.path ? 'Open at the Town' : 'Listed, but the Town returns an error'}
                              </a>
                            </li>
                          ))}
                        </ul>
                      )}
                    </div>
                  )}
                </li>
              )
            })}
          </ul>
        </div>
  )
}
