/**
 * The read-only data API.
 *
 * Everything under /api is a JSON file generated by `scripts/build_api.py` from the
 * analysis database. This Function does three things and nothing else:
 *
 *   1. **Extensionless addresses.** `/api/schema` serves `api/schema.json`. The address
 *      an agent is told to fetch should be the address in the documentation, and
 *      `.json` on the end of every URL is noise that gets dropped and then 404s.
 *
 *   2. **A real 404 with instructions.** A miss under /api returns JSON that says what
 *      exists, not the app shell with a 200. The soft-404 reasoning in ../_notfound.js
 *      applies here with more force: the caller is a program, and a program handed HTML
 *      when it asked for JSON either throws or, worse, parses something.
 *
 *   3. **Cache and CORS headers.** These files are static and identical for everybody,
 *      so they cache hard. CORS is open because the whole point is that anybody can read
 *      this from anywhere -- there is nothing here that is not already public, and no
 *      credential can be attached to a request that has no auth.
 *
 * There is deliberately no rate limiting, because there is nothing to rate limit: no
 * computation happens per request and every response is a cached static asset. That
 * changes when /api/query arrives over D1, and the limiter belongs there rather than
 * here -- rate limiting a CDN hit costs more than the hit.
 */

const JSON_HEADERS = {
  'content-type': 'application/json; charset=utf-8',
  // Static, regenerated only on deploy. Long cache, revalidate in the background.
  'cache-control': 'public, max-age=300, stale-while-revalidate=86400',
  'access-control-allow-origin': '*',
  'access-control-allow-methods': 'GET, HEAD, OPTIONS',
}

/** What to say when a program asks for something that is not here. */
function miss(path) {
  return new Response(JSON.stringify({
    error: 'not_found',
    requested: `/api/${path}`,
    message: 'No such resource. Fetch /api/index for the list of endpoints, or '
      + '/api/schema for the table grain, the sign conventions and the four ways to get '
      + 'a confident wrong answer out of this data.',
    index: '/api/index',
    schema: '/api/schema',
    database: '/data/lunenburg.db',
  }, null, 1) + '\n', { status: 404, headers: JSON_HEADERS })
}

export async function onRequest(context) {
  const { request, env, params } = context

  if (request.method === 'OPTIONS') {
    return new Response(null, { status: 204, headers: JSON_HEADERS })
  }
  if (request.method !== 'GET' && request.method !== 'HEAD') {
    return new Response(JSON.stringify({
      error: 'method_not_allowed',
      message: 'This API is read-only. Use GET.',
    }) + '\n', { status: 405, headers: { ...JSON_HEADERS, allow: 'GET, HEAD, OPTIONS' } })
  }

  const parts = Array.isArray(params.path) ? params.path : [params.path].filter(Boolean)
  const path = parts.join('/')
  // Bare /api is the index, so the root of the API answers rather than 404s.
  const target = path === '' ? 'index' : path

  // Reject traversal before it reaches the asset server rather than trusting it to.
  if (target.includes('..')) return miss(path)

  const url = new URL(request.url)
  const asset = new URL(
    target.endsWith('.json') ? `/api/${target}` : `/api/${target}.json`, url.origin)

  const res = await env.ASSETS.fetch(asset)
  if (res.status !== 200) return miss(path)
  // The asset server answers 200 with the app shell for anything it cannot find, so an
  // HTML body here means the file is absent -- the same tell ../_notfound.js relies on.
  const type = res.headers.get('content-type') || ''
  if (type.includes('text/html')) return miss(path)

  return new Response(res.body, { status: 200, headers: JSON_HEADERS })
}
