#!/usr/bin/env python3
"""Which meeting recordings have captions disabled -- so no transcript can ever be fetched.

    python3 scripts/build_no_captions_report.py          # notes/generated/NO-CAPTIONS.md
    python3 scripts/build_no_captions_report.py --check  # fail if it is stale

Read off sources/data/youtube-no-captions.csv (what the fetcher was refused, and why), the
video classification (titles) and the meetings index (whether the town published minutes
or an agenda for the same board and date, so a reader knows what record survives). Every
row links the video. TJ, 13 September 2026: "generate a report with links about which
meetings have transcripts disabled".
"""
import argparse
import collections
import csv
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NOCAP = os.path.join(ROOT, 'sources', 'data', 'youtube-no-captions.csv')
CLS = os.path.join(ROOT, 'sources', 'data', 'youtube-video-classification.csv')
BOARDS = os.path.join(ROOT, 'sources', 'data', 'youtube-video-boards.csv')
INDEX = os.path.join(ROOT, 'sources', 'meetings', 'index.csv')
OUT = os.path.join(ROOT, 'notes', 'generated', 'NO-CAPTIONS.md')
SITE = 'https://lunenburgbudgetproject.org'


def rows(path):
    with open(path, encoding='utf-8') as fh:
        return list(csv.DictReader(fh))


def build():
    nocap = rows(NOCAP)
    cls = {r['video_id']: r for r in rows(CLS)}
    boards = {r['video_id']: r for r in rows(BOARDS)}
    # what the town published for that board on that date
    # The index keys boards by AgendaCenter id and name; the slug is the path's first
    # segment, which is what the no-captions file carries.
    docs = collections.defaultdict(dict)
    for r in rows(INDEX):
        slug = r['path'].split('/')[0]
        docs[(slug, r['date'])][r['kind']] = SITE + '/docs/meetings/' + r['path']
    by_board = collections.defaultdict(list)
    for r in nocap:
        by_board[r['board_slug']].append(r)
    total = len(nocap)
    reasons = collections.Counter(r['reason'] for r in nocap)
    out = ['# Meeting recordings with captions disabled', '',
           'Generated by `scripts/build_no_captions_report.py` from `sources/data/youtube-no-captions.csv`. '
           'These are recordings the caption fetcher was refused for, with YouTube’s reason — '
           '`TranscriptsDisabled` means the channel has no caption track on the video, auto-generated or '
           'otherwise, so no transcript can be fetched by anyone. Each row says what written record the '
           'town published for the same board and date, from the meetings index.', '',
           f'**{total} recordings**, across {len(by_board)} boards. Reasons: '
           + ', '.join(f'{k} {v}' for k, v in reasons.most_common()) + '.', '']
    no_record = 0
    for slug in sorted(by_board, key=lambda s: -len(by_board[s])):
        rs = sorted(by_board[slug], key=lambda r: r['meeting_date'] or '', reverse=True)
        name = boards.get(rs[0]['video_id'], {}).get('board_name') or slug
        out += [f'## {name} — {len(rs)}', '',
                '| date | recording | reason | written record |', '|---|---|---|---|']
        for r in rs:
            c = cls.get(r['video_id'], {})
            kinds = docs.get((slug, r['meeting_date']), {})
            if kinds:
                rec = ', '.join(f'[{k}]({u})' for k, u in sorted(kinds.items()))
            else:
                rec = '**none found**'
                no_record += 1
            out.append(f"| {r['meeting_date'] or '—'} | [{c.get('title', r['video_id'])}]({r['url']}) | {r['reason']} | {rec} |")
        out.append('')
    out += ['## What this means', '',
            f'{no_record} of the {total} have no agenda or minutes in the town’s AgendaCenter for the same date '
            'either, so the recording is the only record and it cannot be searched. A transcript for those '
            'would need the channel owner to switch captions on (YouTube generates them free once enabled), '
            'or a transcription made from the audio — which this project has not done.', '',
            'The date on each row is read from the video title by `build_youtube_classification.py`; a '
            'recording whose title carries no date is not in the fetcher’s scope and is not listed here.', '']
    return '\n'.join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    text = build()
    if a.check:
        have = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        if have != text:
            print('STALE %s — run build_no_captions_report.py' % os.path.relpath(OUT, ROOT))
            return 1
        print('ok — %s reproduces' % os.path.relpath(OUT, ROOT))
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write(text)
    print('wrote %s' % os.path.relpath(OUT, ROOT))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
