#!/usr/bin/env python3
"""WHERE THE TOWN'S OWN RECORDS DISAGREE ABOUT WHO WORKS FOR IT. An internal note.

    python3 scripts/build_personnel_discrepancies.py [--check]

Writes `notes/generated/PERSONNEL-DISCREPANCIES.md`.

TJ, 22 September 2026: *"lets make a personnel discrepancy internal report so we know."*

THIS IS NOT AN AUDIT AND IT IS NOT FOR PUBLICATION. Rule 8: the job is helping a resident
understand what would work, not cataloguing what the town got wrong. Nothing here is a
finding about the town -- it is a map of where OUR THREE SOURCES cannot be reconciled, so
that the next person to build on them knows which joins hold and which do not.

THE THREE SOURCES, AND WHY THEY DIFFER BY CONSTRUCTION:

  the annual reports   who a department printed in its own roster, FY2011-FY2025. A body
                       that files no report is absent entirely, and 40 times a body was
                       asked and printed `No Report Submitted`
  the staff directory  who the town publishes TODAY, by department, with titles. No date
                       and no year -- a snapshot, and a later fetch will differ
  the gross wages      every name the town paid in a year, with a department column
                       through FY2016 and none after

They are three answers to three different questions -- who a department chose to print,
who the town is advertising now, and who it paid -- so a person in one and not another is
usually not an error. The report separates the differences that are EXPECTED from the few
that are not.

IDENTITY IS SURNAME PLUS FIRST INITIAL, the same rule `build_tenure.py` uses, because
`Josh`/`Joshua Tocci` and `Steve`/`Stephen McKenna` are one person twice. It merges a
little too eagerly on purpose: a false merge shows up here as a title disagreement and
gets read, where a false split silently invents a discrepancy.
"""
import argparse
import collections
import csv
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'sources', 'data')
OUT = os.path.join(ROOT, 'notes', 'generated', 'PERSONNEL-DISCREPANCIES.md')


def who(name):
    parts = [p for p in re.split(r'\s+', (name or '').strip()) if p]
    if not parts:
        return None
    return (parts[-1].lower().strip('.,'), parts[0][:1].lower())


# THE WAGE LIST PRINTS THE SURNAME FIRST, and in capitals: `SULLIVAN PATRICK`,
# `THIBODEAU JEFFREY`. Joining it with the same surname-last rule as everything else
# matched almost nobody — and the first thing that produced was a spectacular false
# finding, that 54 of the town's current staff appear in no record this project holds.
# They do; the join was backwards. A sanity check on two names anybody would recognise
# is what caught it, and it is now run on every build.
def who_wage(name):
    parts = [p for p in re.split(r'\s+', (name or '').strip()) if p]
    if len(parts) < 2:
        return None
    return (parts[0].lower().strip('.,'), parts[1][:1].lower())


def load(path):
    p = os.path.join(DATA, path)
    return list(csv.DictReader(open(p, encoding='utf-8'))) if os.path.exists(p) else []


# THE WORDS A BODY'S NAME IS MADE OF, not the string. `Treasurer And Tax Collector
# Department` and `Tax Collector/Treasurer/Tax Custodian` are one office in two word
# orders, and no amount of containment matching pairs them -- but they share `treasurer`,
# `tax` and `collector`, which is enough and is not enough for anything else.
#
# AND `s` IS NOT A STOPWORD. It was, to fold plurals, and an apostrophe is a word
# boundary: `Veteran's Services` lost the s and `Veterans' Services` kept it, so the same
# department appeared in both columns as missing from the other.
DEPT_NOISE = {'the', 'of', 'and', 'lunenburg', 'department', 'town', 'office', 'pac'}


def dept_words(name):
    n = re.sub(r"\s*\((staff|board|schools|appointed post)\)$", '', name or '', flags=re.I)
    words = re.findall(r"[a-z]+", n.lower().replace("'s", 's'))
    return {w.rstrip('s') for w in words if w not in DEPT_NOISE and len(w) > 2}


def norm_dept(name):
    return ''.join(sorted(dept_words(name)))


def build():
    org = load('org-chart.csv')
    dirs = load('staff-directory.csv')
    wages = load('gross-wages.csv')
    t = []

    last_fy = max((r['fy'] for r in org), default='')
    org_now = {who(r['person']): r for r in org
               if r['fy'] == last_fy and r['person'].strip()}
    org_ever = collections.defaultdict(set)
    for r in org:
        k = who(r['person'])
        if k:
            org_ever[k].add(r['fy'])
    dir_by = {who(r['person']): r for r in dirs if r['person'].strip()}

    t.append('# Where the town’s own records disagree about who works for it\n\n')
    t.append('Generated by `scripts/build_personnel_discrepancies.py`. **Internal.** '
             'Rule 8: this is a map of where OUR sources cannot be reconciled, not a '
             'finding about the town. Three records answer three different questions '
             '— who a department printed in its roster, who the town advertises '
             'today, and who it paid — so a person in one and not another is '
             'usually not an error.\n\n')
    t.append('| source | what it is | people |\n|---|---|---:|\n')
    t.append('| the annual reports | rosters, FY2011–FY%s | %d |\n'
             % (last_fy, len(org_ever)))
    t.append('| the staff directory | the town’s own list, today, undated | %d |\n'
             % len(dir_by))
    paid = {who_wage(r['name']) for r in wages if r['name'].strip()}
    paid.discard(None)
    t.append('| the gross wages | every name paid, by year | %d |\n\n' % len(paid))

    # THE JOIN IS CHECKED BEFORE ANYTHING IS SAID OFF IT. Two people anybody in town
    # could name; if the town's fire chief and police chief are not in the list of
    # everybody the town paid, the join is broken and every count below it is fiction.
    canary = [n for n in ('Patrick A. Sullivan', 'Jeffrey Thibodeau')
              if who(n) not in paid]
    if canary:
        t.append('> **THE WAGE JOIN IS BROKEN** and nothing below that uses it can be '
                 'trusted: %s should be in the list of everybody the town paid and '
                 '%s not.\n\n' % (' and '.join(canary),
                                   'is' if len(canary) == 1 else 'are'))

    # 1. In the directory and in no roster, ever.
    never = [r for k, r in sorted(dir_by.items(), key=lambda kv: kv[1]['department'])
             if k not in org_ever]
    unpaid = [r for r in never if who(r['person']) not in paid]
    t.append('## In the staff directory and in no annual report, ever\n\n')
    t.append('**%d of %d.** The strongest signal here, and mostly not a defect: a '
             'department that files no annual report cannot put anybody in one. Read the '
             'DEPARTMENT column rather than the names — where a whole department '
             'appears, the department is the thing missing.\n\n'
             % (len(never), len(dir_by)))
    bydept = collections.Counter(r['department'] for r in never)
    t.append('| department | in the directory | never in a report |\n|---|---:|---:|\n')
    for d, n in bydept.most_common():
        total = sum(1 for r in dirs if r['department'] == d)
        t.append('| %s | %d | **%d** |\n' % (d, total, n))
    t.append('\n**%d of those %d are not in the gross-wages list either** — in no '
             'record this project holds except the directory. The wage list runs to '
             'FY2025 and the directory is today, so a recent hire is the ordinary '
             'explanation and not a finding.\n' % (len(unpaid), len(never)))
    t.append('\n<details><summary>the %d people</summary>\n\n' % len(never))
    for r in never:
        t.append('- %s — %s, %s\n' % (r['person'], r['title'], r['department']))
    t.append('\n</details>\n\n')

    # 2. On the newest roster and not in the directory.
    gone = [r for k, r in org_now.items() if k and k not in dir_by
            and r['unit_kind'] in ('department', 'school')]
    t.append('## On the FY%s roster and not in the directory\n\n' % last_fy)
    t.append('**%d.** Expected for most: the roster is a year old, the directory is '
             'today, and people leave. It is worth reading only where a whole department '
             'appears — that means the directory does not carry it.\n\n' % len(gone))
    byunit = collections.Counter(r['unit'] for r in gone)
    t.append('| body on the roster | not in the directory |\n|---|---:|\n')
    for u, n in byunit.most_common(14):
        t.append('| %s | %d |\n' % (u, n))
    t.append('\n')

    # 3. Same person, two departments.
    t.append('## The same person in two different departments\n\n')
    rows = []
    for k, d in dir_by.items():
        o = org_now.get(k)
        if not o:
            continue
        a, b = dept_words(o['unit']), dept_words(d['department'])
        if a and b and not (a & b):
            rows.append((d['person'], o['unit'], o['role'], d['department'], d['title']))
    t.append('**%d.** Each is one of three things: somebody who moved, somebody who '
             'holds a post in two places, or a join this project got wrong. All three '
             'are worth knowing and only the third is ours to fix.\n\n' % len(rows))
    if rows:
        t.append('| person | annual report FY%s | staff directory |\n|---|---|---|\n'
                 % last_fy)
        for p, u, ro, dd, ti in sorted(rows):
            t.append('| %s | %s — %s | %s — %s |\n'
                     % (p, u, ro or '—', dd, ti))
    t.append('\n')

    # 4. Same person, same department, different title.
    t.append('## The same person with two different titles\n\n')
    diff = []
    for k, d in dir_by.items():
        o = org_now.get(k)
        if not o or not o['role'] or not d['title']:
            continue
        a, b = o['role'].lower(), d['title'].lower()
        if a not in b and b not in a and (dept_words(o['unit']) & dept_words(d['department'])):
            diff.append((d['person'], o['unit'], o['role'], d['title']))
    t.append('**%d.** The annual report prints a rank and the directory prints a job, '
             'and they are often both right — `Chief of Department` and `Chief & '
             'Forest Warden` are one man with two hats. This list is here so that a '
             'page choosing ONE of them knows it is choosing.\n\n' % len(diff))
    if diff:
        t.append('| person | body | the report says | the directory says |\n'
                 '|---|---|---|---|\n')
        for p, u, ro, ti in sorted(diff)[:40]:
            t.append('| %s | %s | %s | %s |\n' % (p, u, ro, ti))
        if len(diff) > 40:
            t.append('\n...and %d more.\n' % (len(diff) - 40))
    t.append('\n')

    # 5. Departments in one list and not the other.
    t.append('## Departments in one record and not the other\n\n')
    # EVERY BODY IN THE CHART, not only the departments. The directory files the staff
    # who support a board under that board's name -- the Conservation Agent under
    # Conservation Commission, the clerk under the Zoning Board of Appeals -- so
    # comparing against departments alone reported nine boards we hold as missing.
    od = {norm_dept(r['unit']): r['unit'] for r in org}
    dd = {norm_dept(r['department']): r['department'] for r in dirs}
    # MATCHED BY CONTAINMENT, because the two records spell the same body differently:
    # `Assessor's Department` against `Board Of Assessors`, `Treasurer And Tax Collector
    # Department` against `Tax Collector/Treasurer/Tax Custodian`, `Veteran's Services
    # Department` against `Veterans' Services`. Listing those as departments missing from
    # one record would be reporting our own spelling as a gap.
    def matched(name, others):
        mine = dept_words(name)
        for o in others:
            if not o:
                continue
            theirs = dept_words(o)
            # Two shared words, or every word of the shorter name. `Board Of Assessors`
            # and `Assessor's Department` share exactly one, and it is the only one
            # either of them has that means anything.
            if len(mine & theirs) >= min(2, len(mine), len(theirs)):
                return True
        return False

    only_dir = sorted(v for v in dd.values() if not matched(v, od.values()))
    only_org = sorted(v for v in od.values() if not matched(v, dd.values()))
    t.append('| only in the staff directory | only in the annual reports |\n|---|---|\n')
    for a, b in zip(only_dir + [''] * len(only_org), only_org + [''] * len(only_dir)):
        if a or b:
            t.append('| %s | %s |\n' % (a, b))
    t.append('\n**The right column is long and that is expected.** It is almost all '
             'volunteer boards — a body with no paid staff has nobody for a staff '
             'directory to list, and the Finance Committee and the Library Trustees are '
             'not missing from it, they are not the kind of thing it holds.\n\n')
    t.append('**The left column is the one to read, and four of it are deliberate.** '
             'Animal Control sits inside the Police Department here because the '
             'department’s own FY27 chart puts `ACO Kathy Comeau` under the Chief, '
             'and the Electrical, Plumbing/Gas and Weights & Measures inspectors sit '
             'inside Building. What is left is **Accounting** and **Human Resources** '
             '— two departments this project could not see at all until the '
             'directory was fetched, because neither files an annual report and neither '
             'head is an APPOINTED OFFICIAL, which is the single blind spot both of the '
             'other sources share.\n')
    return ''.join(t)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    text = build()
    if a.check:
        old = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        if old != text:
            print('STALE %s' % OUT)
            return 1
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, 'w', encoding='utf-8').write(text)
    print('wrote %s (%d lines)' % (os.path.relpath(OUT, ROOT), text.count('\n')))
    return 0


if __name__ == '__main__':
    sys.exit(main())
