#!/usr/bin/env python3
"""EVERY KNOWN PROBLEM WITH THE DATA, in one place, mostly measured rather than typed.

    python3 scripts/build_data_problems.py [--check]

Writes `notes/generated/DATA-PROBLEMS.md`.

TJ, 22 September 2026, after the FY2022 Fire roster turned out to be missing from the
town's own book: *"we should flag this finding for FY22 fire somehow. are we keeping track
of data problems?"*

NOT IN ONE PLACE, WE WERE NOT. `money-gaps.csv` holds questions the archive cannot answer
and is published at `/what-we-cannot-answer`; `roster-completeness.csv` measures how short
a chart is; `check_org_charts.py` counts what is structurally wrong; the extractors print
what they threw away and store none of it. Four kinds of problem, four places, and nothing
that tells somebody starting tomorrow which numbers to distrust.

THREE KINDS, AND KEEPING THEM APART IS THE WHOLE POINT:

  the DOCUMENT is defective   the town published something incomplete or inconsistent.
                              Nothing we do closes it. The FY2022 annual report prints
                              nine career firefighters and no call roster at all
  OUR READING is thin         the document is fine and the extractor does not get all of
                              it. Ours to fix, and it should never be described as a gap
                              in what the town publishes
  the QUESTION has no answer  nobody published the thing. That is `money-gaps.csv` and it
                              stays there; this document points at it rather than
                              restating it

Mixing them is how a project tells a resident the town does not publish something it
publishes every year -- rule 13c, which this archive has broken five times.

MOSTLY GENERATED. The measured sections are read from the datasets on every build, so a
problem that gets fixed disappears from this document by itself. Only `document-defects.csv`
is typed, because a defect in somebody else's printing cannot be derived -- it has to be
found by a person and written down with its evidence.
"""
import argparse
import collections
import csv
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'sources', 'data')
OUT = os.path.join(ROOT, 'notes', 'generated', 'DATA-PROBLEMS.md')


def load(name):
    p = os.path.join(DATA, name)
    return list(csv.DictReader(open(p, encoding='utf-8'))) if os.path.exists(p) else []


def build():
    t = ['# Every known problem with the data\n\n',
         'Generated by `scripts/build_data_problems.py`. Three kinds of problem, kept '
         'apart on purpose: a **document** that is defective, a **reading** of ours that '
         'is thin, and a **question** nobody published an answer to. Mixing them is how '
         'a project ends up telling a resident the town does not publish something it '
         'publishes every year.\n\n']

    defects = load('document-defects.csv')
    t.append('## 1. The document is defective\n\n')
    t.append('**%d.** The town published something incomplete or inconsistent. Nothing '
             'this project does closes these; they are recorded so that a figure read '
             'off one is never mistaken for a measurement of the world. Typed by hand, '
             'because a defect in somebody else’s printing cannot be derived.\n\n'
             % len(defects))
    for d in defects:
        t.append('**FY%s — %s, %s.** %s\n\n' % (d['fy'], d['document'], d['body'],
                                                     d['what']))
        t.append('- *how it was found:* %s\n' % d['how_found'])
        t.append('- *evidence:* %s\n\n' % d['evidence'])

    short = [r for r in load('roster-completeness.csv') if int(r['shortfall']) > 0]
    t.append('## 2. The chart is short, and the town’s own count says by how much\n\n')
    t.append('**%d department-years.** A shortfall is only a fact when something the '
             'town said supplies the denominator, so each row carries its basis. Some of '
             'these are section 1 in disguise — the document is short — and '
             'some are section 3 — our reading is. The basis says which.\n\n'
             % len(short))
    t.append('| FY | body | names | of | because |\n|---|---|---:|---:|---|\n')
    for r in sorted(short, key=lambda r: (-int(r['shortfall']), r['unit'])):
        t.append('| %s | %s | %s | %s | %s |\n'
                 % (r['fy'], r['unit'], r['named'], r['stated'], r['basis']))

    ours = [g for g in load('money-gaps.csv') if g['side'] == 'extraction']
    t.append('\n## 3. Our reading is thin\n\n')
    t.append('**%d.** The document is fine and the extractor does not get all of it. '
             'These are OURS to fix and must never be described as something the town '
             'does not publish.\n\n' % len(ours))
    for g in ours:
        t.append('- **%s** %s\n' % (g['what'], g['why']))

    gaps = load('money-gaps.csv')
    by = collections.Counter(g['side'] for g in gaps)
    t.append('\n## 4. Nobody published an answer\n\n')
    t.append('**%d questions** in `sources/data/money-gaps.csv`, rendered at '
             '`/what-we-cannot-answer`. Not restated here — that registry is the '
             'single place for them and a second copy would go stale. By side: %s.\n'
             % (len(gaps), ', '.join('%s %d' % (k, v) for k, v in sorted(by.items()))))
    return ''.join(t)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    text = build()
    if a.check:
        old = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        if old != text:
            print('STALE %s' % OUT)
            return 1
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, 'w', encoding='utf-8').write(text)
    print('wrote %s' % os.path.relpath(OUT, ROOT))
    return 0


if __name__ == '__main__':
    sys.exit(main())
