#!/usr/bin/env python3
"""How the town's ledger is STRUCTURED and NAMED — and every trap in it we have hit.

    python3 scripts/build_ledger_structure.py
    python3 scripts/build_ledger_structure.py --check

Writes `notes/reference/LEDGER-STRUCTURE.md`.

WHY THIS FILE EXISTS SEPARATELY FROM SCHEMA.md

`SCHEMA.md` documents OUR database — tables we built, and their grain. This documents the
TOWN's data as it arrives: how an account number is put together, what a fund number means,
what the columns that look alike actually distinguish, and above all **what the names do
not say.**

Every entry below was learned by getting something wrong first. The naming section in
particular is not trivia. Three real money nodes were lost in a single afternoon because a
filter matched a name, and the name was not the thing:

  - the athletics revolving fund is called `CHAPTER 658 REVOLVING FUND`
  - the pension assessment is called `WRRS ASSESSMENT`, its account `COUNT[Y] RET`
  - school retiree health is `SCHRETHLTH`, and it lives under the insurance department

**The rule this file is really about: never identify a thing by its name in this ledger.**
Identify it by its account number, its fund number, or its department — those are assigned
and stable. The name is a ten-character abbreviation typed by a person.
"""

import argparse
import os
import sqlite3

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB = os.path.join(ROOT, 'sources', 'data', 'lunenburg.db')
OUT = os.path.join(ROOT, 'notes', 'reference', 'LEDGER-STRUCTURE.md')

# What a name turned out to mean, and HOW that was established. Every row here cost a
# wrong turn; the evidence column is the point, because "we think it means X" is how the
# next one gets lost.
DECODER = [
    ('`CHAPTER 658 REVOLVING FUND`', 'fund 1301',
     'The athletics revolving fund',
     'Its cash journal comments read `CHAPTER 658 ATHLET` and it issues refunds to '
     'families by name.'),
    ('`WRRS ASSESSMENT`', 'dept 820',
     'Worcester Regional Retirement System — the town’s pension assessment',
     'The only account under it is `COUNT[Y] RET`; the FY2019 annual report’s budget '
     'narrative prints *"Worcester Regional Retirement ($1,354,353)"* as an expenditure '
     'category.'),
    ('`SCHRETHLTH`', '`0100-19142-570018`',
     'School retiree health insurance',
     'Sits under dept 914 INSURANCE beside `TNRETHLTHI` (town retiree health) and '
     '`HEALTH INS` (active town employees).'),
    ('`SCHCOSTREI`', 'general fund revenue',
     'Special education circuit breaker reimbursement',
     'Same magnitude as fund 2640 `SPECIAL ED CIRCUIT BREAKER`. **Whether these are the '
     'same money booked twice or two different flows is NOT established.**'),
    ('`FBCYBUDGET`', 'general fund revenue',
     'Free cash and transfers in', 'Ranked with the other financing sources.'),
    ('`SCHRESSTIP`', '`0100-12101-519021`',
     'A school-related stipend inside the police department',
     '**Inferred from the abbreviation.** The amount is immaterial and the expansion is '
     'a guess, marked as one.'),
    ('`MTGS/SCHOO`', 'several departments',
     'Meeting expenses, at a school — not school spending',
     'Under Fire, Land Use, Finance Committee, Town Clerk and others, at $500–$5,050. A '
     'name match on "SCHOO" pulls these in and they are not school money.'),
]


def db():
    if not os.path.exists(DB):
        raise SystemExit(f'{DB} missing. Run: python3 scripts/build_db.py')
    c = sqlite3.connect(DB)
    c.row_factory = sqlite3.Row
    return c


def shapes(c):
    """The grammar of an account number, counted rather than described."""
    out = {}
    for (aid,) in c.execute('SELECT account_id FROM account'):
        key = '-'.join(
            ('S' + 'N' * (len(p) - 1)) if p[:1] == 'S' else ('N' * len(p) if p.isdigit()
                                                             else 'X' * len(p))
            for p in aid.split('-'))
        out[key] = out.get(key, 0) + 1
    return sorted(out.items(), key=lambda kv: -kv[1])


def render(c):
    L = []
    a = L.append
    a('# The town’s ledger — structure, naming, and every trap in it\n')
    a('**Generated by `scripts/build_ledger_structure.py`. Do not edit.**\n')
    a('`SCHEMA.md` documents *our* database. This documents the *town’s* data as it '
      'arrives: how an account number is built, what a fund number means, what the columns '
      'that look alike actually distinguish, and above all what the names do not say.\n')
    a('> **The rule underneath all of it: never identify a thing by its name in this '
      'ledger.** Identify it by account number, fund number or department — those are '
      'assigned and stable. The name is a ten-character abbreviation typed by a person.\n')

    a('\n## 1. The shape of an account number\n')
    a('| shape | count | what it is |')
    a('|---|---:|---|')
    meaning = {
        4: 'fund–org–object, the ordinary detail account',
        3: 'fund–department, a roll-up row',
    }
    for key, n in shapes(c)[:6]:
        parts = key.split('-')
        if len(parts) == 2:
            what = 'fund–department — a **roll-up** row, not a detail account'
        elif parts[1].startswith('S'):
            what = 'fund–org–object where the org is **S-prefixed**'
        else:
            what = 'fund–org–object, an ordinary detail account'
        a(f'| `{key}` | {n:,} | {what} |')
    a('')
    n_s = c.execute("SELECT COUNT(*) FROM account WHERE account_id LIKE '0100-S%'").fetchone()[0]
    n_300 = c.execute("SELECT COUNT(*) FROM account WHERE dept='300' AND level='account'").fetchone()[0]
    n_bad = c.execute("""SELECT COUNT(*) FROM account WHERE dept='300' AND level='account'
                         AND account_id NOT LIKE '0100-S%'""").fetchone()[0]
    a(f'**The `S` prefix means school.** {n_s} accounts carry it and all of them are '
      f'department 300; department 300 has {n_300} detail accounts and {n_bad} of them '
      f'lack the prefix. It is an exact match in both directions, which makes '
      f'`account_id LIKE \'0100-S%\'` a **structural** way to find school spending — one '
      f'that does not depend on any name.\n')

    a('\n## 2. Two grains of the same money, told apart only by period\n')
    rows = c.execute("""SELECT l.period, a.level, COUNT(*) n, SUM(l.original) v
                        FROM ledger_snapshot l JOIN account a USING (account_id)
                        WHERE l.fy=2026 AND a.fund='0100' AND a.account_type='expense'
                        GROUP BY l.period, a.level ORDER BY l.period""").fetchall()
    a('| period | grain | rows | total |')
    a('|---:|---|---:|---:|')
    for r in rows:
        a(f'| {r["period"]} | {r["level"]} | {r["n"]:,} | ${r["v"]:,.0f} |')
    if len(rows) == 2:
        a(f'\nThe same general fund, twice, ${abs(rows[0]["v"]-rows[1]["v"]):,.0f} apart. '
          f'They are **different MUNIS reports**, and `period` is the only column that '
          f'distinguishes them — so a query without it adds one report to the other.\n')

    a('\n## 3. Three columns that look optional and are not\n')
    a('| column | if you omit it |')
    a('|---|---|')
    a('| `level` | department roll-ups are summed **on top of their own detail** |')
    a('| `account_type` | revenue is stored **negative** and nets against expense — this '
      'is how the town’s whole budget once computed as **minus $997,871** |')
    a('| `period` | two different reports are added together (see above) |')
    a('\nThis is the same rule that governs `status` on the annual-report extracts and '
      '`v1` on the page tables: **a column that says what a row IS cannot be skipped '
      'because the rows look alike.** It has now been got wrong on three unrelated '
      'datasets.\n')

    a('\n## 4. Fund numbers, by range\n')
    a('| range | funds | example |')
    a('|---|---:|---|')
    for r in c.execute("""SELECT substr(fund,1,2) pre, COUNT(*) n, MIN(name) ex
                          FROM fund GROUP BY pre ORDER BY pre"""):
        a(f'| `{r["pre"]}xx` | {r["n"]} | {r["ex"]} |')
    a('\nSchool money is spread across `13xx` (revolving), `15xx`, `22xx` (lunch) and '
      '`26xx`–`29xx` (grants). **There is no single range that means "school"**, which is '
      'why the node list enumerates funds by number rather than filtering on a name.\n')

    a('\n## 5. The ten-character ceiling\n')
    led = c.execute("SELECT MAX(LENGTH(name)) FROM account WHERE level='account'").fetchone()[0]
    ten = c.execute("SELECT COUNT(*) FROM account WHERE level='account' AND LENGTH(name)=10").fetchone()[0]
    book = c.execute('SELECT MAX(LENGTH(label)) FROM budget_line').fetchone()[0]
    a(f'The longest account name in the ledger is **{led} characters**, and {ten:,} '
      f'accounts sit exactly at it. The district’s own budget book runs to {book}. MUNIS '
      f'truncates hard, and the casualties are readable in the data: `COUNT RET`, '
      f'`SCHRETHLTH`, `PS TEACH R`, `PRE-SCHOOL T UIT ION` once OCR gets involved.\n')
    a('Two consequences that have already bitten:\n')
    a('- **Names collide.** `MS GUIDANC` and `HS GUIDANC` are distinct rows in the '
      'district’s book and the same ten characters minus one in the ledger. This is why '
      '`crosswalk` is deliberately empty: the function code joins a **category**, never a '
      'line.\n')
    a('- **A name cannot be searched reliably.** Anything that matters must be found by '
      'number.\n')

    a('\n## 6. The decoder — what a name turned out to mean, and how we know\n')
    a('| name | where | what it actually is | how that was established |')
    a('|---|---|---|---|')
    for name, where, what, how in DECODER:
        a(f'| {name} | {where} | {what} | {how} |')

    a('\n## 7. Things the structure hides completely\n')
    a('- **A grant fund can spend without booking revenue in the same year.** Nine did in '
      'FY2026. Any query that finds school money by looking at revenue misses every one '
      'of them, and they are real spending.\n')
    a('- **A department is not a purpose.** School retiree health is in the insurance '
      'department; a school resource stipend is in the police department; meeting expenses '
      '*at* a school are in five departments and are not school money at all.\n')
    a('- **Function codes outrun their names.** The district’s budget book names 45 of '
      'them. The ledger uses more. A code the book does not name is shown here by the '
      'accounts inside it rather than named from the DESE chart of accounts, because '
      'naming it from general knowledge would be a derived thing quoted as an observed '
      'one.\n')
    return '\n'.join(L) + '\n'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    c = db()
    fresh = render(c)
    rel = os.path.relpath(OUT, ROOT)
    if args.check:
        if not os.path.exists(OUT):
            raise SystemExit(f'{rel} does not exist. Run without --check.')
        if open(OUT, encoding='utf-8').read() != fresh:
            raise SystemExit(f'STALE: {rel} no longer reproduces.\n'
                             f'  Run: python3 scripts/build_ledger_structure.py')
        print(f'ok: {rel} still reproduces')
        return
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write(fresh)
    print(f'wrote {rel} ({len(fresh):,} bytes)')


if __name__ == '__main__':
    main()
