#!/usr/bin/env python3
"""The agentic backlog: every stream of machine reading this project runs, how far each
has got, and the order it works in.

    python3 scripts/build_agentic_backlog.py       # write notes/generated/AGENTIC-BACKLOG.md

TJ, 17 September 2026: "Sounds like we just have some Agentic processing. Put them into a
list and work them in priority order, newest first. Last 2 years is most important across
everything than deeper for more." Four streams, one rule: the last two years across every
board before anything older, newest first inside each. Counts are derived; the refresh
rewrites this daily.
"""
import csv
import datetime as dt
import glob
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'scripts'))
OUT = os.path.join(ROOT, 'notes', 'generated', 'AGENTIC-BACKLOG.md')
RECENT = (dt.date.today() - dt.timedelta(days=730)).isoformat()


def read(p):
    return list(csv.DictReader(open(p, encoding='utf-8'))) if os.path.exists(p) else []


def split(dates_done, dates_todo):
    r = lambda ds: (sum(1 for d in ds if d >= RECENT), sum(1 for d in ds if d < RECENT))
    return r(dates_done), r(dates_todo)


def transcripts():
    # ONE ROW PER RECORDING. youtube-video-boards.csv is one row per (video, board), so a
    # joint body's meeting appears under each board that was in it -- a Tri-Board meeting is
    # four rows. Counting rows counts that recording four times in a backlog of recordings.
    rows = read(os.path.join(ROOT, 'sources', 'data', 'youtube-video-boards.csv'))
    rows = list({r['video_id']: r for r in rows}.values())
    have = {os.path.basename(p)[-16:-5] for p in glob.glob(os.path.join(ROOT, 'sources', 'data', 'youtube-transcripts', '*', '*.json'))}
    nocap = {r['video_id'] for r in read(os.path.join(ROOT, 'sources', 'data', 'youtube-no-captions.csv'))}
    done = [r['meeting_date'] for r in rows if r['video_id'] in have]
    todo = [r['meeting_date'] for r in rows if r['video_id'] not in have and r['video_id'] not in nocap and r['meeting_date']]
    return done, todo


def recording_minutes():
    import refresh
    have = [os.path.basename(p)[:10] for p in glob.glob(os.path.join(ROOT, 'sources', 'data', 'recording-minutes', '*', '*.json'))]
    todo = [t['meeting_date'] for t in refresh.minutes_targets(refresh.policy())]
    return have, todo


def official_votes():
    import extract_official_votes as E
    files = E.minutes_files()
    have = {os.path.relpath(p, E.OUT)[:-5] for p in glob.glob(os.path.join(E.OUT, '*', '*.json'))}
    done = [e['date'] for e in files if '%s/%s-%s' % (e['board_slug'], e['date'], e['docid']) in have]
    todo = []
    for e in files:
        if '%s/%s-%s' % (e['board_slug'], e['date'], e['docid']) in have:
            continue
        body = open(e['path'], encoding='utf-8', errors='replace').read()
        if len(re.sub(r'\s+', ' ', body)) >= E.MIN_CHARS:
            todo.append(e['date'])
    return done, todo


def ocr():
    import ocr_scanned_minutes as O
    done = [r['date'] for r in O.registry().values()]
    todo = [c['date'] for c in O.candidates()]
    return done, todo


def main():
    streams = [
        ('Captions for recordings', 'fetch_youtube_transcripts.py — free, throttled by YouTube; run_transcript_backfill.sh sweeps the last two years across every board, then the rest; the refresh takes 12 a day', transcripts()),
        ('Our minutes of recordings', 'write_recording_minutes.py — claude -p, ~0.09% of the weekly allowance each; the refresh writes 3 a day, last two years first, then the three budget boards deeper', recording_minutes()),
        ('Votes from the town’s minutes', 'extract_official_votes.py — claude -p on the small model, ~0.03% each, every quote checked verbatim; the refresh reads 40 a day, newest first across every board', official_votes()),
        ('OCR of scanned minutes', 'ocr_scanned_minutes.py — macOS Vision, local and free, ~30 s each; the refresh reads 40 a day, newest first; a scan read here enters search and the votes stream', ocr()),
    ]
    b = io.StringIO()
    b.write('# The agentic backlog\n\n')
    b.write('Generated by `scripts/build_agentic_backlog.py`, %s. **The rule:** the last two years (since %s) across every board before anything older; newest first inside each stream. Costs are the calibrated share of the plan’s weekly allowance (CLAUDE.md, ~/.claude).\n\n' % (dt.date.today().isoformat(), RECENT))
    b.write('| stream | done, last 2 yrs | to do, last 2 yrs | done, older | to do, older | how |\n|---|---:|---:|---:|---:|---|\n')
    for name, how, (done, todo) in streams:
        (dr, do), (tr, to) = split(done, todo)
        b.write('| %s | %d | **%d** | %d | %d | %s |\n' % (name, dr, tr, do, to, how))
    b.write('\n**Not in any stream, by choice:** minutes-writing for boards outside the policy file waits on `sources/data/recording-minutes-policy.csv`; conclusions on the finance pages are a per-owner writing job, not a batch.\n')
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, 'w', encoding='utf-8').write(b.getvalue())
    print(b.getvalue())


if __name__ == '__main__':
    main()
