#!/usr/bin/env python3
"""What the generic annual-report extracts are, and what may not be done with them.

Rule 12 says a source arrives with its provenance, not retrofitted. Four of the
annual-report datasets were hand-built and carry a `PROVENANCE-*.md` written beside them.
The twelve produced by `scripts/extract_tables.py` had none, and they are the ones that
most need one, because they are the ones nobody has checked by reading.

This is generated so its figures cannot drift from the data (rule 2). It says what each
dataset is, how much of it is checked, and the four things that are true of all of them.

    python3 scripts/build_report_tables_provenance.py
"""

import collections
import csv
import glob
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'sources', 'data')
OUT = os.path.join(DATA, 'PROVENANCE-report-tables.md')

WHAT = {
    'appropriations': "the Town Accountant's schedule of the year that closed, and the "
                      "town meeting's omnibus budget for the year ahead — two different "
                      "tables, told apart by `table_family`",
    'trust-funds': 'the trust and stabilisation funds, balance and activity by fund',
    'debt': 'debt outstanding, issued and retired',
    'capital-projects': 'capital project authorisations and what was spent against them',
    'valuation': "the assessors' valuation and tax rate history",
    'elections': 'the vote, by candidate or question, by precinct',
    'officials': 'who held which town office, and until when',
    'dept-activity': 'counts a department reports of what it did that year',
    'enrollment-mcas': 'enrolment by school and MCAS results',
    'monty-tech': 'the Montachusett Regional Vocational Technical assessment and enrolment',
    'gross-wages': 'the gross wage paid to every town employee',
    'vital-records': 'births, marriages and deaths recorded by the Town Clerk',
}


def main():
    out = ['# The generic annual-report extracts — what they are, and what they are not',
           '',
           '**Generated by `scripts/build_report_tables_provenance.py`. Do not edit.**',
           '']
    rows_by = {}
    for path in sorted(glob.glob(os.path.join(DATA, 'report-*.csv'))):
        name = os.path.basename(path)[len('report-'):-len('.csv')]
        if name == 'anomalies':
            continue
        rows_by[name] = list(csv.DictReader(open(path)))

    total = sum(len(v) for v in rows_by.values())
    checked = sum(1 for v in rows_by.values() for r in v if r['status'] == 'checked')
    failed = sum(1 for v in rows_by.values() for r in v if r['status'] == 'check failed')
    none = sum(1 for v in rows_by.values() for r in v if r['status'] == 'no check')

    out += [
        '**The index for all of this is `notes/reference/ANNUAL-REPORTS.md`** — every',
        'dataset, where it lives, what state it is in, and what is still uncaptured.',
        '`notes/reference/BACKUP.md` says how many copies of each thing exist.',
        '',
        f'{total:,} rows across {len(rows_by)} tables, read out of sixteen annual town',
        'reports by one extractor. The address of every row — the document, the',
        "publisher's own filename and our copy's sha256 — is in",
        '`notes/generated/DATASET-PROVENANCE.md` and `sources/data/dataset-provenance.csv`.',
        'This document is the other half of rule 12: what the figures are.',
        '',
        '## These are transcriptions. Most are not verified',
        '',
        f'| status | rows | what it means |',
        '|---|---:|---|',
        f'| `checked` | {checked:,} | a check existed and it passed |',
        f'| `check failed` | {failed:,} | a check existed and it did not pass |',
        f'| `no check` | {none:,} | the table prints no total; verify by reading the page |',
        '',
        'A table that prints no total is **not** less authoritative. These reports are the',
        'official record — Town Manager and Finance Committee approved, carrying tables',
        'exported from MUNIS — so the town\'s figure is not what is in question. Only our',
        'transcription of it is. `no check` says nothing about the town and everything',
        'about what arithmetic can reach.',
        '',
        '**Nothing here may be aggregated without splitting on `status` first.**',
        '',
        '## `v1` is an ordinal. It is not a column',
        '',
        'The value columns are named `v1`…`v8`, and that name means *the first, second,',
        'third column of THIS PAGE that held figures*. The column ruler is built per page,',
        'so `v1` is not the same printed column on two pages of the same table: FY2011',
        'page 62 has TOTAL AVAILABLE there, page 64 has APPROPRIATED, page 61 has only',
        'three of the six columns at all.',
        '',
        'Where the table states an identity that fixes it, the columns are named and',
        '`column_meaning` says which is which — for the appropriations schedule,',
        '`available = appropriated + forward` and',
        '`balance = available − expended − encumbered`. Where it does not,',
        '`column_meaning` says `not established`, and the reconciliation string says the',
        'v-numbers are ordinals in those words.',
        '',
        '**Read `column_meaning` before you read a value.** A sum of `v1` across pages is',
        'a sum of different things.',
        '',
        '## What the other columns carry',
        '',
        '| column | what it holds |',
        '|---|---|',
        '| `kind` | `row`, `subtotal`, `grand_total`, `footnote`, `page_number` |',
        '| `row_check` | how this row was proved, or why it could not be |',
        '| `derived_cell` | a value inferred from the row\'s own total — never written into a value column |',
        '| `table_family` | which of a dataset\'s tables this row is from |',
        '| `line_no` | the report\'s own line numbering, where it numbers its lines |',
        '| `column_meaning` | what each `v` column is, on this row\'s page |',
        '| `ruler_spanned` | the row crossed a column boundary; its cells may be cut wrong |',
        '| `repaired_cells` | figures `amount()` had to repair to read |',
        '| `unparsed_cells` | cells that plainly held a figure and did not parse |',
        '',
        '## The datasets',
        '',
        '| dataset | rows | checked | check failed | no check | what it is |',
        '|---|---:|---:|---:|---:|---|',
    ]
    for name in sorted(rows_by):
        rs = rows_by[name]
        c = collections.Counter(r['status'] for r in rs)
        out.append(f'| `report-{name}` | {len(rs):,} | {c["checked"]:,} | '
                   f'{c["check failed"]:,} | {c["no check"]:,} | '
                   f'{WHAT.get(name, "—")} |')

    out += [
        '',
        '## Two families the extractor no longer writes',
        '',
        'Receipts and special revenue have dedicated extractors that tie —',
        '`sources/data/annual-report-receipts.csv` against the report\'s own printed GRAND',
        'TOTAL, and `sources/data/special-revenue-funds.csv` against the fund identity',
        '(forward + receipts − disbursements = carried forward). The generic reading of',
        'those families produced a second, worse copy of the same table, and two files for',
        'one thing is an ambiguity a reader cannot resolve. `extract_tables.py` refuses to',
        'write them and names the file that is the figure.',
        '',
        '## What these do not tell you',
        '',
        '- **A budget line is a net appropriation, not a cost** (rule 11). Grants, fees and',
        '  revolving funds pay for real staff and appear in none of these tables.',
        '- **A count of names is not a staffing level.** The wage list and the officials',
        '  list carry no FTE and no funding source.',
        '- **A `check failed` row is not a wrong row.** It means our total and the printed',
        '  total disagree; the row may be right and a neighbour wrong.',
        '- **A reconciled total does not verify a row.** It verifies the sum. A page can',
        '  tie with two offsetting errors in it, and one did for a year.',
        '',
        '## How to check one',
        '',
        '    python3 scripts/verify_report_tables.py         # every stated reconciliation, recomputed',
        '    python3 scripts/verify_against_page.py <dataset> <edition> [--pages N]',
        '',
        'The first is arithmetic and proves only that the CSV agrees with itself. The',
        'second renders the page beside the rows taken off it, and a person has to look.',
        '',
    ]
    open(OUT, 'w').write('\n'.join(out))
    print(f'wrote {os.path.relpath(OUT, ROOT)} — {total:,} rows, {len(rows_by)} datasets')


if __name__ == '__main__':
    main()
