#!/usr/bin/env python3
"""Merge the per-report inventories into one catalogue of what the annual reports hold.

Sixteen documents were read end to end, page by page, with no list of things to look for --
because every extractor written against a list had silently succeeded for the years that
matched it and failed for the rest. `sources/data/inventory/FY*.json` is what came back:
819 blocks of structured data, described in each year's own terms.

This merges them into:

    sources/data/annual-report-catalogue.csv     one row per table instance
    notes/generated/ANNUAL-REPORT-CATALOGUE.md   the same, readable, grouped across years

**The grouping across years is derived, and it is the weakest thing here.** The same table
is called different things in different years -- and sometimes nothing at all, since several
print their title at the *bottom* of the page and the employee compensation list carries no
heading in any year. Rows are clustered by token overlap on the plain-English name the
reader gave them, never on the printed heading, and the printed heading is carried through
untouched so the clustering can be checked rather than trusted. Rule 7: the cluster is a
hypothesis about which tables are the same table.

    python3 scripts/build_report_catalogue.py
"""

import collections
import csv
import glob
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INV = os.path.join(ROOT, 'sources', 'data', 'inventory')
OUT_CSV = os.path.join(ROOT, 'sources', 'data', 'annual-report-catalogue.csv')
OUT_MD = os.path.join(ROOT, 'notes', 'generated', 'ANNUAL-REPORT-CATALOGUE.md')

STOP = {'of', 'the', 'and', 'by', 'for', 'town', 'lunenburg', 'fy', 'fiscal', 'year',
        'annual', 'report', 'summary', 'detail', 'list', 'table', 'schedule'}


def key_of(name):
    """A clustering key from the reader's plain-English name.

    Deliberately crude and deliberately not built from the printed heading, because the
    printed heading is the thing that differs between years -- that is the whole finding.
    """
    words = [w for w in re.findall(r'[a-z]+', (name or '').lower())
             if w not in STOP and len(w) > 2]
    return ' '.join(sorted(set(words))[:4]) or 'unclassified'


def main():
    rows = []
    for path in sorted(glob.glob(os.path.join(INV, 'FY*.json'))):
        d = json.load(open(path))
        stem = os.path.basename(path).replace('.json', '')
        for t in d.get('tables', []):
            rows.append({
                'fy': d.get('fy'),
                'edition': stem,
                'document': d.get('document', ''),
                'name': t.get('name', ''),
                'printed_heading': t.get('printed_heading', ''),
                'pages': t.get('pages', ''),
                'what_it_is': t.get('what_it_is', ''),
                'grain': t.get('grain', ''),
                'columns': ' | '.join(t.get('columns') or []),
                'layout': t.get('layout', ''),
                'printed_total': t.get('printed_total', ''),
                'approx_rows': t.get('approx_rows', ''),
                'extractable': t.get('extractable', ''),
                'notes': t.get('notes', ''),
                'cluster': key_of(t.get('name')),
            })

    os.makedirs(os.path.dirname(OUT_CSV), exist_ok=True)
    with open(OUT_CSV, 'w', newline='') as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    write_md(rows)
    print(f'{len(rows)} table instances from {len(glob.glob(os.path.join(INV, "FY*.json")))} '
          f'documents')
    print(f'wrote {os.path.relpath(OUT_CSV, ROOT)}')
    print(f'wrote {os.path.relpath(OUT_MD, ROOT)}')

    by = collections.defaultdict(set)
    anchored = collections.defaultdict(set)
    for r in rows:
        by[r['cluster']].add(str(r['fy']))
        if r['printed_total']:
            anchored[r['cluster']].add(str(r['fy']))
    print('\nthe 25 most widely-held tables (years held / years with a printed total):')
    for k, ys in sorted(by.items(), key=lambda kv: -len(kv[1]))[:25]:
        print(f'  {len(ys):>2} / {len(anchored.get(k, ())):>2}   {k}')


def write_md(rows):
    years = sorted({str(r['fy']) for r in rows})
    by = collections.defaultdict(list)
    for r in rows:
        by[r['cluster']].append(r)

    L = ['# What the annual town reports actually contain', '',
         '**Generated by `scripts/build_report_catalogue.py`. Do not edit.**', '',
         f'{len(rows)} blocks of structured data, found by reading all sixteen reports end',
         'to end with **no list of things to look for**. That method was chosen because',
         'every extractor written against a list of expected tables had silently succeeded',
         'for the years that matched it and failed for the rest — and the years it missed',
         'read as years the town published nothing.', '',
         '## How to read this', '',
         'The **printed heading** column is the point. The same table is called different',
         'things in different years, and sometimes nothing at all: several print their title',
         'at the *bottom* of the page, and the employee compensation list carries no heading',
         'in any year. Any search keyed on a heading finds a subset and reports the rest as',
         'absent.', '',
         'A table with a **printed total** can be checked against itself. One without can be',
         'transcribed and never verified — that distinction matters more than how many rows',
         'it has.', '',
         'The **grouping across years is derived** and is the weakest thing in this file.',
         'Rows are clustered by the plain-English name the reader gave them, never by the',
         'printed heading. Treat a cluster as a hypothesis that these are the same table.',
         '']

    L.append('## Coverage')
    L.append('')
    L.append('| what | years held | of which have a printed total |')
    L.append('|---|---:|---:|')
    ranked = sorted(by.items(), key=lambda kv: (-len({str(r['fy']) for r in kv[1]}), kv[0]))
    for k, rs in ranked:
        ys = {str(r['fy']) for r in rs}
        an = {str(r['fy']) for r in rs if r['printed_total']}
        if len(ys) >= 3:
            L.append(f'| {k} | {len(ys)} | {len(an)} |')
    L.append('')

    L.append('## By year')
    L.append('')
    for y in years:
        mine = [r for r in rows if str(r['fy']) == y]
        L.append(f'### FY{y} — {len(mine)} blocks')
        L.append('')
        L.append('| pages | what it is | printed heading | rows | total printed | extractable |')
        L.append('|---|---|---|---:|---|---|')
        for r in sorted(mine, key=lambda r: str(r['pages'])):
            head = (r['printed_heading'] or '*(none printed)*').replace('|', '\\|')
            L.append(f"| {r['pages']} | {r['name'].replace('|', '/')} | `{head}` | "
                     f"{r['approx_rows']} | {(r['printed_total'] or '—')[:44]} | "
                     f"{r['extractable']} |")
        L.append('')

    os.makedirs(os.path.dirname(OUT_MD), exist_ok=True)
    with open(OUT_MD, 'w') as fh:
        fh.write('\n'.join(L) + '\n')


if __name__ == '__main__':
    main()
