"""Write the categorised discrepancy list for review by the Town.

    python3 scripts/build_discrepancy_review.py

Writes `notes/generated/REVIEW-DISCREPANCIES.md`.

Generated, not written, for rule 2's reason: every figure is derived here, so re-running
after any ingest keeps the document current instead of quoting a number the data no
longer produces.

THREE THINGS THIS FILE IS CAREFUL ABOUT

1.  **Every row carries a locator on BOTH sides.** The ledger account number, and the
    workbook's own row number and printed line name. A reader must be able to open each
    document and land on the row, not go searching for it. That is also what makes a
    disagreement checkable rather than something to take on trust.

2.  **Every account has exactly ONE category.** Athletics dues appeared in three at once
    -- the same account counted three times, inflating two totals. Category E owns the
    two accounts whose workbook figure is not their appropriation; B and F exclude them.

3.  **Categories are ordered by what needs an answer, not by dollar size.** The largest
    number here is a classification question where both documents hold the money and
    nothing is missing. The smallest is $1,896 of instructional materials. Sorting by
    amount would put the benign item first and the control question fourth.

Nothing here is an accusation, and where the archive cannot say which document is right
it says so. The companion `notes/generated/REQUEST-CODING.md` is the longer version for the
Superintendent; both are generated from the same comparison so they cannot drift apart.
"""
import collections
import os
import re
import sys
from datetime import date

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_code_reconciliation_xlsx import load, match, m  # noqa: E402
from minutes_decisions import DECISIONS, SILENT, url, verify  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'notes', 'generated', 'REVIEW-DISCREPANCIES.md')

# Named for what each document IS to the reader, not for what it is to this project.
# "the ledger" and "the workbook" are our words; a Town Manager reads a year-to-date
# report and a school budget.
YTD_FILE = 'FY26 BUDGET YEAR TO DATE REPORT (9-1-2026).xlsx'
YTD_WHERE = 'sheet `ACCOUNT DETAIL`, column E'
BUD_FILE = 'FY27 budget projection workbook, FY26 FINAL BUDGET column'
BUD_WHERE = 'sheet `FY27 Budget Projection`, column B'


# A hand edit to the output is lost the next time this runs, and nothing warns
# you. The banner says so in the file itself, where somebody about to edit it is
# actually looking -- an HTML comment, so it is invisible wherever the Markdown is
# rendered.
BANNER = ('<!-- GENERATED by scripts/build_discrepancy_review.py — DO NOT EDIT.\n     Hand edits are overwritten on the next run. Change the script instead. -->\n\n')

def d(v):
    return f'${v:,.0f}' if v >= 0 else f'-${abs(v):,.0f}'


def dc(v):
    """With cents. $1.93 rounded to the dollar prints as "$2", which reads as a
    suspiciously round number rather than as the rounding it is."""
    return f'${v:,.2f}' if v >= 0 else f'-${abs(v):,.2f}'


def dec(key):
    """One board decision, rendered with its quote and a link to the minutes."""
    board, date, _p, _u, quote, verdict, note = DECISIONS[key]
    mark = {'approved': 'Voted and itemised',
            'approved-partial': 'Voted, destinations not recorded',
            'requested': 'Requested, not a transfer',
            'silent': 'No vote recorded',
            'contradicts': 'Said on the record, and it does not fit'}[verdict]
    return ('**%s** — %s, %s ([minutes](%s))<br>“%s”<br>%s'
            % (mark, board, date, url(key), ' '.join(quote.split()), note))


def main():
    bad = verify()
    if bad:
        for b in bad:
            print('FAIL', b)
        return 1
    led, book = load()

    def acc(nm, fn):
        """An account by name AND function code. The name alone is not unique: three
        accounts are called DUES/FEES, and taking the first returned the $1,687 supplies
        line where the $29,965 athletics one was meant."""
        hit = [r for r in led if r['name'].strip() == nm and r['function'] == fn]
        if len(hit) != 1:
            raise SystemExit('%s/%s matches %d accounts, expected 1' % (nm, fn, len(hit)))
        return hit[0]

    def bk(lbl):
        hit = [r for r in book if r['line_item'].strip() == lbl]
        if len(hit) != 1:
            raise SystemExit('workbook line %r matches %d rows, expected 1'
                             % (lbl, len(hit)))
        return hit[0]

    def brow(lbl):
        """The workbook's own row number, so nobody has to search for the line."""
        return 'row %s' % bk(lbl)['row']

    A, B, label, uncoded = (collections.defaultdict(list),
                            collections.defaultdict(list), {}, [])
    for r in led:
        A[r['function']].append(r)
    for r in book:
        g = re.match(r'\s*(\d{4})', r['function_group'] or '')
        if not g:
            if abs(m(r['fy26_final'])) >= 0.5:
                uncoded.append(r)
            continue
        B[g.group(1)].append(r)
        lbl = re.sub(r'^\d{4}\s*-\s*', '', (r['function_group'] or '').strip()).strip()
        label.setdefault(g.group(1), [])
        if lbl and lbl not in label[g.group(1)]:
            label[g.group(1)].append(lbl)

    codes = sorted(set(A) | set(B))

    def tot(c):
        return (sum(m(x['original']) for x in A[c]),
                sum(m(x['fy26_final']) for x in B[c]))

    off = [c for c in codes if abs(tot(c)[0] - tot(c)[1]) > max(1.0, len(A[c]))]
    naked = [r for r in led if abs(m(r['original'])) < 0.5
             and abs(m(r['expended'])) >= 0.5 and abs(m(r['transfers'])) < 0.5]

    # E owns these two; B and F exclude them so no account is counted twice.
    basis = [(acc('ATH INS', '3510'), bk('Athletic Insurance')),
             (acc('DUES/FEES', '3510'), bk('Athletic Dues & Fees'))]
    owned_a = {r['account'] for r, _ in basis}
    # Category D owns these two: both have an appropriation AND a school budget line, so
    # neither belongs in a category about accounts with nothing appropriated. They were
    # in both, which double-counted $91,460.
    owned_a |= {acc('SCHSALRESE', '0300')['account'], acc('REP OFF MA', '4230')['account']}
    owned_b = {r['line_item'].strip() for _, r in basis}

    blind, split = [], []
    for c in codes:
        pairs, spare = match(B[c], A[c])
        blind += [a for a in spare
                  if abs(m(a['transfers'])) >= 0.5 and a['account'] not in owned_a]
        if c in off:
            continue
        ub = [b for b, a, _ in pairs if a is None and abs(m(b['fy26_final'])) >= 0.5
              and b['line_item'].strip() not in owned_b]
        sp = [a for a in spare
              if (abs(m(a['original'])) >= 0.5 or abs(m(a['revised'])) >= 0.5)
              and a['account'] not in owned_a]
        if ub:
            split.append((c, ub, sp))

    # Which basis is the workbook's FY26 column on? Only testable where a transfer made
    # the appropriation and the revised budget differ.
    moved = [r for r in led if abs(m(r['transfers'])) >= 0.5]
    bo = br = bx = 0
    for c in codes:
        prs, spr = match(B[c], A[c])
        for b, a, _ in prs:
            if a is None or abs(m(a['transfers'])) < 0.5:
                continue
            v = m(b['fy26_final'])
            if abs(v - m(a['original'])) <= 1.0:
                bo += 1
            elif abs(v - m(a['revised'])) <= 1.0:
                br += 1
        bx += len([a for a in spr if abs(m(a['transfers'])) >= 0.5])

    led_tot = sum(m(r['original']) for r in led)
    bk_tot = sum(m(r['fy26_final']) for r in book)

    def munis_of(c):
        return sum(m(x['original']) for x in A[c])

    def book_of(c):
        return sum(m(x['fy26_final']) for x in B[c])

    # How much of the appropriation sits in a code the two documents disagree about. Not
    # money at risk -- money that cannot be compared between the two documents.
    affected = sum(max(munis_of(c), book_of(c)) for c in off)
    sw = [r for r in led if r['name'].strip() == 'SOCWORKSAL']
    ell, ace = bk('District Wide Specials (ELL)'), bk('ACE Special Ed Resource Rm Teacher')
    ca, sr = bk('Curriculum Adoption'), bk('Salary Reserve')
    rom = acc('REP OFF MA', '4230')

    L = []
    P = L.append
    P('# FY2026 school budget — points for review')
    P('')
    P('**To:** Town Manager and Town Accountant, Town of Lunenburg  ')
    P('**Generated:** %s by `scripts/build_discrepancy_review.py`' % date.today())
    P('')
    P('Comparing two documents for the school department, FY2026:')
    P('')
    P('- **the YTD report** — the Town Accountant’s `%s`, %s' % (YTD_FILE, YTD_WHERE))
    P('- **the school budget** — the district’s %s, %s' % (BUD_FILE, BUD_WHERE))
    P('')
    P('Both state amounts against the same function codes. **%d of %d codes agree.**'
      % (len(codes) - len(off), len(codes)))
    P('')
    P('## Why this matters')
    P('')
    P('Following a single line from what was budgeted to what was spent means finding it')
    P('in both documents. Everything below is a case where that cannot be done, and each')
    P('kind breaks it differently:')
    P('')
    P('| what breaks | what it prevents | scale |')
    P('|---|---|---:|')
    P('| **Codes do not match** — %d of %d function codes hold different totals | '
      'Comparing a whole category. Guidance is %s in one document, %s in the other | '
      '**%s** · %.0f%% of the appropriation |'
      % (len(off), len(codes), d(munis_of('2710')), d(book_of('2710')),
         d(affected), affected / led_tot * 100))
    P('| **Lines do not match** — one account against two budget lines | Attributing the '
      'money to a school, even when the total is right | %s |'
      % d(sum(m(b['fy26_final']) for _, ub, _ in split for b in ub)))
    P('| **One line, two amounts** — one document before a transfer, one after | Knowing '
      'which figure is the budget | %s |' % d(abs(m(basis[0][0]['transfers']))))
    P('| **Spending with no budget** — %d accounts, nothing appropriated, no transfer | '
      'Tracing a charge to whatever authorised it | %s |'
      % (len(naked), d(sum(m(r['expended']) for r in naked))))
    P('| **Zero budget, real spending** — %d accounts funded entirely by transfer | '
      'Reading the school budget as what a programme has | %s |'
      % (len(blind), d(sum(abs(m(r['transfers'])) for r in blind))))
    P('| **Transfers not named** — approved 24 June 2026 | Reconciling the year to what '
      'was voted | 4 transfers |')
    P('')
    P('The consequence is the same in every case: **the year cannot be checked line by')
    P('line** — not by a resident, not by the Finance Committee, and not by the district')
    P('checking its own books against the Town’s.')
    P('')
    P('**No money is missing, and this is not an audit.** Across both school departments')
    P('the two documents reconcile to **%s** in total. Every problem here is about where'
      % dc(abs(bk_tot - led_tot)))
    P('a figure sits and whether it can be found in both places, not about how much there')
    P('is.')
    P('')
    P('Each item gives the account number and the school budget row, so it can be opened')
    P('in both documents without searching. **Ordered by what needs an answer, not by')
    P('size.** Where the archive cannot say which document is right it says so, and')
    P('guesses are marked as guesses.')
    P('')
    P('| | category | items | sum involved | what it needs | in the minutes |')
    P('|---|---|---:|---:|---|---|')
    cats = [
        ('A', '**Spent without budget**', '%d accounts' % len(naked),
         sum(m(r['expended']) for r in naked), '**How these were authorised**',
         'One contradicted, five silent'),
        ('B', 'Nothing appropriated, funded by transfer', '%d accounts' % len(blind),
         sum(abs(m(r['transfers'])) for r in blind), 'What each transfer paid for',
         'One voted, three silent'),
        ('C', 'Accounts not aligned', '4 pairs of codes',
         sum(m(r['original']) for r in sw) + abs(m(ell['fy26_final'])
                                                 - m(ace['fy26_final']))
         + m(sr['fy26_final']) + m(rom['original']),
         'Which code is authoritative', 'No vote on the coding itself'),
        ('D', 'Two figures on different bases', '2 accounts',
         abs(m(basis[0][0]['transfers'])), 'Which basis the school budget column uses',
         '**Voted, and explained**'),
        ('E', 'Same total, different lines', '%d code' % len(split),
         sum(m(b['fy26_final']) for _, ub, _ in split for b in ub),
         'Which line the money sits against', 'Partly voted'),
    ]
    for k, cat, n, amt, need, vote in cats:
        P('| **%s** | %s | %s | %s | %s | %s |' % (k, cat, n, d(amt), need, vote))
    P('')
    P('**The sums are amounts involved, not money missing, and they do not add up.**')
    P('')
    P('---')
    P('')
    P('# A. Spent without budget')
    P('')
    P('*Nothing appropriated, no transfer in, and money paid out. %d accounts, %s.*'
      % (len(naked), d(sum(m(r['expended']) for r in naked))))
    P('')
    P('| YTD report account | name | spent | in the school budget |')
    P('|---|---|---:|---|')
    for r in sorted(naked, key=lambda r: -m(r['expended'])):
        # NOT 'no line carries this'. The workbook does carry lines under these codes --
        # Kindergarten Aides/Regular is printed at $0 -- they simply have no amount. Which
        # blank line corresponds to which account is a name judgement, so the count and
        # the code are given and the reader decides.
        blanks = [b for b in B[r['function']] if abs(m(b['fy26_final'])) < 0.5]
        P('| `%s` | %s | %s | code `%s` — %d line%s under it, none with an amount |'
          % (r['account'], r['name'].strip(), d(m(r['expended'])), r['function'],
             len(blanks), '' if len(blanks) == 1 else 's'))
    P('')
    P('The two kindergarten accounts are %s of it. The FY26 approved budget published the'
      % d(sum(m(r['expended']) for r in naked if 'KIND' in r['name'].upper())))
    P('kindergarten line as a cut, so the question is where these charges were provided')
    P('')
    P('for.')
    P('')
    P('**In the minutes.**')
    P('')
    P('%s' % dec('kindergarten'))
    P('')
    P('%s' % dec('kindergarten_fy27'))
    P('')
    P('For the other four accounts: %s' % ' '.join(SILENT.split()))
    P('')
    P('The school budget does carry a **Kindergarten Aides/Regular** line, %s,'
      % brow('Kindergarten Aides/Regular'))
    P('printed at $0, and a **Kindergarten Paraprofessionals** line, %s, left blank.'
      % brow('Kindergarten Paraprofessionals'))
    P('')
    P('# B. Nothing appropriated, funded entirely by transfer')
    P('')
    P('*The school budget appropriates **nothing** to these %d accounts. Each was given'
      % len(blind))
    P('money by transfer during the year. One is nearly all of it.*')
    P('')
    P('| YTD report account | name | appropriated | moved | spent |')
    P('|---|---|---:|---:|---:|')
    for r in sorted(blind, key=lambda r: -abs(m(r['transfers']))):
        P('| `%s` | %s | %s | %s | %s |'
          % (r['account'], r['name'].strip(), d(m(r['original'])),
             d(m(r['transfers'])), d(m(r['expended']))))
    P('')
    P('**In the minutes.**')
    P('')
    P('%s' % dec('phys_ed'))
    P('')
    P('The other three: %s' % ' '.join(SILENT.split()))
    P('')
    P('# C. Accounts not aligned')
    P('')
    P('*The same money under a different function code in each document. Both documents')
    P('hold it; they disagree only about where it sits. The guess is mine, from the')
    P('amounts, and is not established.*')
    P('')
    P('| codes | in the YTD report | in the school budget | amount | my guess |')
    P('|---|---|---|---:|---|')
    P('| `2710` vs `2900` | %s | %s | %s | Same money, filed two ways. Nothing missing |'
      % ('; '.join('`%s`' % r['account'] for r in sorted(sw, key=lambda r: r['account'])),
         '; '.join('%s %s' % (lbl, brow(lbl)) for lbl in
                   ('P.S. Social Worker', 'E.S. Social Worker', 'M.S Social Worker',
                    'H.S. Social Worker')),
         d(sum(m(r['original']) for r in sw))))
    P('| `2310` ↔ `2320` | `%s` DWSPECIALI and `%s` ACERESROOM | District Wide Specials '
      '(ELL) %s and ACE Special Ed Resource Rm Teacher %s | %s | One document has the two '
      'the wrong way round |'
      % (acc('DWSPECIALI', '2310')['account'], acc('ACERESROOM', '2320')['account'],
         brow('District Wide Specials (ELL)'),
         brow('ACE Special Ed Resource Rm Teacher'),
         d(abs(m(ell['fy26_final']) - m(ace['fy26_final'])))))
    P('| `0300` vs none | `%s` SCHSALRESE | Salary Reserve, %s — under a section heading '
      'with no code | %s | The same line |'
      % (acc('SCHSALRESE', '0300')['account'], brow('Salary Reserve'),
         d(m(sr['fy26_final']))))
    P('| `4230` vs `4220` | `%s` REP OFF MA | P.S. Repair Office Machines, %s | %s | The '
      'same line, coded two ways |'
      % (rom['account'], brow('P.S. Repair Office Machines'), d(m(rom['original']))))
    P('')
    P('**The full code comparison**, for anyone checking:')
    P('')
    P('| code | school budget group | YTD report | school budget | difference |')
    P('|---|---|---:|---:|---:|')
    for c in sorted(off, key=lambda c: -abs(tot(c)[0] - tot(c)[1])):
        a, b = tot(c)
        P('| `%s` | %s | %s | %s | **%s** |'
          % (c, ' / '.join(label.get(c, [])) or '*no group under this code*',
             d(a), d(b), d(abs(a - b))))
    P('')
    P('**In the minutes.** No vote in the archive decides which coding is right for any')
    P('of these four. The nearest thing is a March 2026 transfer that names one of the')
    P('accounts as a source, without touching how it is coded:')
    P('')
    P('%s' % dec('sped_materials'))
    P('')
    P('# D. Two figures on different bases')
    P('')
    P('*Only accounts with a transfer can show which basis the school budget uses,')
    P('because only there do the appropriation and the revised budget differ.')
    P('There are %d such accounts: the school budget matches the appropriation on %d,'
      % (len(moved), bo))
    P('the revised budget on %d, and %d cannot be told apart.*' % (br, bx))
    P('')
    P('| YTD report account | appropriated | moved | revised | school budget says | school budget line |')
    P('|---|---:|---:|---:|---:|---|')
    for a, b in basis:
        P('| `%s` %s | %s | %s | %s | **%s** | %s, %s |'
          % (a['account'], a['name'].strip(), d(m(a['original'])), d(m(a['transfers'])),
             d(m(a['revised'])), d(m(b['fy26_final'])), b['line_item'].strip(),
             brow(b['line_item'].strip())))
    P('')
    P('Insurance matches the revised figure rather than the appropriation; dues and fees')
    P('matches neither. Which basis does the school budget column use, and for which '
      'lines?')
    P('')
    P('**In the minutes — this is the one item that is settled, and the district'
      ' explained it itself.**')
    P('')
    P('%s' % dec('athletic_basis'))
    P('')
    P('So the $20,000 is a transfer the School Committee approved on the record, for a')
    P('reason it stated on the record. What is left is the narrower question of which')
    P('figure the school budget column is meant to show, because it reflects this')
    P('transfer and not the 75 others tested.')
    P('')
    P('# E. Same total, different lines')
    P('')
    P('*The code total agrees, so nothing is missing and no dollar is unaccounted for.')
    P('The money sits against different lines inside the code — which is what happens')
    P('when one account covers what the school budget splits across schools.*')
    P('')
    P('| code | YTD report | school budget |')
    P('|---|---|---|')
    for c, ub, sp in split:
        left = '; '.join('`%s` %s %s' % (a['account'], a['name'].strip(),
                                         d(m(a['original']))) for a in sp) or '—'
        P('| `%s` | %s | %s |'
          % (c, left,
             '; '.join('%s %s, %s' % (b['line_item'].strip(), d(m(b['fy26_final'])),
                                      brow(b['line_item'].strip())) for b in ub) or '—'))
    P('')
    P('**In the minutes.** A March 2026 vote moved $462.07 into the Primary School')
    P('special education instructional materials line, which is the same family of')
    P('accounts — but it names the Primary School, not the two schools at issue here.')
    P('')
    P('# What the minutes do and do not record')
    P('')
    P('**Every transfer goes to a vote.** `Review & Approve Line Item Transfers, Warrants')
    P('& Donations` is a standing School Committee agenda item, and it appears at every')
    P('meeting in FY26.')
    P('')
    P('**What the minutes then say varies.** Some meetings itemise each transfer with')
    P('both account names and the amount — the athletic insurance vote is a model of it.')
    P('Others record only that transfers were approved. The clearest case is the last')
    P('meeting of the year:')
    P('')
    P('%s' % dec('june_four'))
    P('')
    P('**Every FY26 meeting has now been read.** The 5 November 2025 minutes were')
    P('unreadable when this comparison was first made and have since been extracted; they')
    P('record two transfers, both of which tie to the ledger exactly and neither of which')
    P('touches anything in this document:')
    P('')
    P('%s' % dec('november'))
    P('')
    P('**One referenced document is not in the archive.** A March 2026 transfer of')
    P('$54,548.50 was made against a list of destinations that the minutes say was')
    P('"provided to the committee (and available online)":')
    P('')
    P('%s' % dec('soa'))
    P('')
    P('## What would close most of this in one step')
    P('')
    P('**The account master** — the mapping from each MUNIS account number to its')
    P('function code and description. **C and E answer themselves from it** — those are')
    P('the two where both documents hold the money and only the coding differs.')
    P('')
    P('**A, B and D need a word from somebody.** A mapping cannot say how a charge was')
    P('authorised against an account with no budget, say what a transfer paid for, or')
    P('explain which basis a column is on.')
    P('')
    P('**And one document would help with all of it:** the list of destinations behind')
    P('the $54,548.50 March transfer, which the minutes say was provided to the committee')
    P('and is not in the public archive.')
    P('')
    P('## Method, in four lines')
    P('')
    P('The join is the function code in the fourth segment of the MUNIS account string')
    P('(`0100-3-300-2330-51-2-13-1-511203`), which is the same code the school budget')
    P('prints over each group. Within a code, lines are paired **by amount**, which is not a')
    P('key: it shows a figure of that size exists on both sides, never that the two are')
    P('the same line. Full working in `sources/data/fy26-code-reconciliation.xlsx`.')
    P('')

    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write(BANNER + '\n'.join(L) + '\n')
    print('wrote %s' % os.path.relpath(OUT, ROOT))
    print('  A %d unbudgeted  B 1 no-account  C %d transfers  D %d codes  E 2 bases  '
          'F %d split' % (len(naked), len(blind), len(off), len(split)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
