#!/usr/bin/env python3
"""The Finance Committee delivery, as a list of reading tasks, and how far each has got.

    python3 scripts/build_fincom_tasks.py          # write the progress page and the map
    python3 scripts/build_fincom_tasks.py --check  # fail if either is stale, or a file has no task

TJ, 5 October 2026: *"can you break down the work for ingestion from this dump into itemized
tasks or subtasks? i want to see what needs to be done, and track progress"* -- and the aim
behind it: *"read everything from this dump into readable format, then we can analyze it into
useful insights."*

THE TASKS ARE WRITTEN BY HAND, in `sources/data/finance-committee-tasks.csv`, because grouping
documents into a unit of work is a judgement: one extractor per KIND of document, not one per
file. Everything else is derived here.

EVERY DOCUMENT BELONGS TO EXACTLY ONE TASK, or this refuses to write. The universe is the
delivery register -- every file filed, redacted or withheld, so the private ones are counted
too -- and each is assigned to the first task whose `documents` pattern matches its delivered
name, private tasks (K) first and the four catch-all presentation buckets (I1-I4) last. A file that matches nothing would be a file nobody is going to
read, which is exactly the thing this list exists to make impossible.

A TASK IS DONE WHEN ITS `done_when` HOLDS, and `state` says so. Text has been extracted for
every document already; the tasks are about TABLES -- turning a workbook or a ledger into a
dataset that ties to a total the document prints (CLAUDE.md, rule 13).
"""
import argparse
import csv
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TASKS = os.path.join(ROOT, 'sources', 'data', 'finance-committee-tasks.csv')
REGISTER = os.path.join(ROOT, 'sources', 'data', 'finance-committee-delivery.csv')
MAP = os.path.join(ROOT, 'sources', 'data', 'finance-committee-task-docs.csv')
OUT = os.path.join(ROOT, 'notes', 'generated', 'FINANCE-COMMITTEE-INGEST.md')
STATES = ('todo', 'in-progress', 'done', 'not-needed')
IN_SCOPE = ('filed', 'redacted', 'withheld')


def load():
    tasks = list(csv.DictReader(open(TASKS, encoding='utf-8')))
    for t in tasks:
        if None in t or t['state'] not in STATES:
            sys.exit(f'{TASKS}: task {t.get("id")} is malformed or has an unknown state')
    docs = [r for r in csv.DictReader(open(REGISTER, encoding='utf-8'))
            if r['disposition'] in IN_SCOPE]
    return tasks, docs


def assign(tasks, docs):
    # PRIVATE TASKS FIRST, THE CATCH-ALL PRESENTATION BUCKETS LAST. I1-I4 match a whole budget
    # year's folder (`^FY27 Budget/`), so in file order they claimed the trust fund records
    # before J1 could -- J1 had zero documents while an agent did its work by finding the
    # files itself. Found 5 October 2026. Specific before general.
    BROAD = {'I1', 'I2', 'I3', 'I4'}
    order = sorted(tasks, key=lambda t: 0 if t['id'].startswith('K')
                   else (2 if t['id'] in BROAD else 1))
    out, orphans = [], []
    for d in docs:
        for t in order:
            if re.search(t['documents'], d['delivered_as'], re.I):
                out.append({'task': t['id'], 'delivered_as': d['delivered_as'],
                            'disposition': d['disposition'], 'key': d['key'],
                            'sha256': d['sha256']})
                break
        else:
            orphans.append(d['delivered_as'])
    if orphans:
        sys.exit('documents with no task -- add them to a task in '
                 'finance-committee-tasks.csv:\n  ' + '\n  '.join(orphans))
    return out


def render(tasks, mapping):
    n = {}
    for m in mapping:
        n[m['task']] = n.get(m['task'], 0) + 1
    by_state = {s: [t for t in tasks if t['state'] == s] for s in STATES}
    work = [t for t in tasks if t['state'] != 'not-needed']
    b = io.StringIO()
    b.write('# The Finance Committee delivery: reading it into tables\n\n')
    b.write('Generated by `scripts/build_fincom_tasks.py` from '
            '`sources/data/finance-committee-tasks.csv`. Do not edit here: change a task\'s '
            '`state` there and re-run.\n\n')
    b.write(f'**{len(by_state["done"])} of {len(work)} tasks done**, '
            f'{len(by_state["in-progress"])} in progress, {len(by_state["todo"])} to do'
            f' -- covering {len(mapping)} documents, every one assigned to a task.\n\n')
    b.write('Text is already extracted for every public document. A task is about the '
            'TABLES: a dataset that ties to a total the document itself prints.\n\n')
    for prio in sorted({t['priority'] for t in tasks}):
        group = [t for t in tasks if t['priority'] == prio]
        b.write(f'## Priority {prio}\n\n')
        b.write('| | task | FY | docs | state | done when |\n|---|---|---:|---:|---|---|\n')
        for t in group:
            mark = {'done': '✅', 'in-progress': '🔄', 'todo': '⬜', 'not-needed': '➖'}[t['state']]
            b.write(f'| {t["id"]} | {t["task"]} | {t["fy"]} | {n.get(t["id"], 0)} | '
                    f'{mark} {t["state"]} | {t["done_when"]} |\n')
        b.write('\n')
    return b.getvalue()


def render_map(mapping):
    b = io.StringIO()
    w = csv.DictWriter(b, fieldnames=['task', 'delivered_as', 'disposition', 'key', 'sha256'],
                       lineterminator='\n')
    w.writeheader()
    w.writerows(sorted(mapping, key=lambda m: (m['task'], m['delivered_as'])))
    return b.getvalue()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    tasks, docs = load()
    mapping = assign(tasks, docs)
    page, tab = render(tasks, mapping), render_map(mapping)
    if a.check:
        stale = [p for p, want in ((OUT, page), (MAP, tab))
                 if not os.path.exists(p) or open(p, encoding='utf-8').read() != want]
        if stale:
            sys.exit('stale: ' + ', '.join(os.path.relpath(p, ROOT) for p in stale)
                     + ' -- run: python3 scripts/build_fincom_tasks.py')
        print(f'ok: {len(tasks)} tasks, {len(mapping)} documents, all assigned')
        return
    open(OUT, 'w', encoding='utf-8').write(page)
    open(MAP, 'w', encoding='utf-8').write(tab)
    print(f'wrote {os.path.relpath(OUT, ROOT)} and {os.path.relpath(MAP, ROOT)}: '
          f'{len(tasks)} tasks, {len(mapping)} documents')


def stream():
    """For the agentic backlog: (done dates, to-do dates), one per task that is real work.

    A task is dated by its fiscal year's first day, so the backlog's two-year split puts
    FY2025 onward in 'last 2 years' the way it does every other stream.
    """
    tasks, _ = load()
    d = lambda t: f'{int(t["fy"]) - 1}-07-01'
    work = [t for t in tasks if t['state'] != 'not-needed']
    return ([d(t) for t in work if t['state'] == 'done'],
            [d(t) for t in work if t['state'] != 'done'])


if __name__ == '__main__':
    main()
