#!/usr/bin/env python3
"""Where every figure about a town department or board comes from, department by department.

    python3 scripts/build_town_data_provenance.py
    python3 scripts/build_town_data_provenance.py --check

Writes `notes/reference/TOWN-DATA-PROVENANCE.md`.

TJ, 21 September 2026: *"did you describe how each board's/dept's data is fetched so we
remember in the future? provenance and all that"*. Partly, and in the wrong places. Every
generator documents itself in its own docstring and every dataset has a line in the source
catalogue -- but a person asking *what do we know about the Fire Department and how do we
know it* had to read five files and join them in their head.

GENERATED, NEVER MAINTAINED, for the reason rule 2 gives: a hand-written inventory of
one's own datasets is the thing most certain to be wrong within a month, and this one
would be wrong in the direction that matters -- claiming coverage that has gone.

WHAT IT RECORDS FOR EACH DEPARTMENT AND BOARD

  * WHICH DATASET holds each kind of figure -- money, posts, staffing, named roster.
  * WHICH YEARS are actually in it, counted from the rows rather than from the plan.
  * WHAT PROVES IT. Every one of these datasets carries a check the DOCUMENT offers about
    itself: group totals against the printed grand total, a heading stating a membership
    against the names beneath it, a stated strength against a named roster. The state of
    that check per year is the honest answer to "can I quote this", and it is repeated
    here so nobody has to go and find it.
  * WHAT IS MISSING, and whether it is missing from the town or from us. Those are
    different facts and this project has confused them repeatedly -- most of today, in
    fact: `the town does not print who works there` was our silence, not theirs.
"""
import argparse
import collections
import csv
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'scripts'))

import town_budget_data as D                                    # noqa: E402

DATA = os.path.join(ROOT, 'sources', 'data')
OUT = os.path.join(ROOT, 'notes', 'reference', 'TOWN-DATA-PROVENANCE.md')

SOURCES = [
    ('money — what Town Meeting voted', 'report-appropriations.csv',
     'scripts/extract_tables.py appropriations',
     'the omnibus budget in each annual town report — THE YEAR AHEAD, so the FY2024 book '
     'carries the FY2025 budget',
     'the twelve group totals against the grand total the same page prints'),
    ('posts — every elected seat, appointed seat and officer', 'town-personnel.csv',
     'scripts/extract_personnel.py',
     'the ELECTED OFFICIALS and APPOINTED OFFICIALS listing, nine pages a year',
     'a heading stating a membership against the names printed beneath it'),
    ('staffing — what a department says it employs', 'department-staffing.csv',
     'scripts/extract_department_staffing.py',
     'the prose of each department’s own report; no heading names it in any year',
     'none available except where a roster exists to compare against'),
    ('roster — staff by name', 'department-rosters.csv',
     'scripts/extract_department_rosters.py',
     'the Police `Department Personnel` and Fire `Roster of the Lunenburg Fire '
     'Department` pages, both set in two columns',
     'the named roster against the strength the department states in prose'),
]


def read(name):
    p = os.path.join(DATA, name)
    if not os.path.exists(p):
        return []
    with open(p, encoding='utf-8') as fh:
        return list(csv.DictReader(fh))


def span(years):
    ys = sorted({int(y) for y in years if str(y).isdigit()})
    if not ys:
        return '—', 0
    runs, start, prev = [], ys[0], ys[0]
    for y in ys[1:]:
        if y != prev + 1:
            runs.append((start, prev))
            start = y
        prev = y
    runs.append((start, prev))
    return ', '.join('FY%d' % a if a == b else 'FY%d–FY%d' % (a, b)
                     for a, b in runs), len(ys)


def build():
    budget = D.load()
    personnel = read('town-personnel.csv')
    staffing = read('department-staffing.csv')
    rosters = read('department-rosters.csv')

    t = ['# Where every figure about a town department comes from\n',
         '\nGenerated by `scripts/build_town_data_provenance.py`. Do not edit — the '
         'counts are read off the datasets, so a coverage claim here cannot outlive the '
         'data behind it.\n']

    t.append('\n## The four sources, and what each one proves\n\n'
             '| what | dataset | written by | read from | what checks it |\n'
             '|---|---|---|---|---|\n')
    for what, ds, gen, frm, chk in SOURCES:
        t.append('| %s | `%s` | `%s` | %s | %s |\n' % (what, ds, gen, frm, chk))

    # ---- money, by department -------------------------------------------------------
    t.append('\n## Money, department by department\n\n'
             'The omnibus budget in an annual report is the year AHEAD. Detail reconciles '
             'for the three years below; every other year has a printed grand total and '
             'no department breakdown read yet.\n\n'
             '| department | years with a figure | FY%d | check |\n|---|---|---:|---|\n'
             % budget['detail_years'][-1])
    for slug, name, _p in D.GROUPS:
        years = [y for y in budget['detail_years'] if budget['groups'][y].get(slug)]
        sp, _n = span(years)
        last = budget['groups'][budget['detail_years'][-1]].get(slug)
        rc = budget['reconcile'][budget['detail_years'][-1]]
        t.append('| %s | %s | $%s | %s |\n'
                 % (name, sp, format(int(last or 0), ','),
                    'group totals tie to the printed grand total'
                    if abs(rc['difference']) < 0.01 else
                    'ties to %+.2f — the town’s own arithmetic' % rc['difference']))
    t.append('\nThe voted TOTAL is held for %s. FY2026 is a total and nothing else: the '
             'FY2025 report prints Article 10 as prose and no department table exists for '
             'it in any form.\n' % span(budget['totals'])[0])

    # ---- posts ----------------------------------------------------------------------
    by_post = collections.defaultdict(list)
    for r in personnel:
        by_post[r['post']].append(r)
    checks = collections.Counter(r['size_check'] for r in personnel)
    t.append('\n## Posts and boards\n\n`town-personnel.csv`, %s, %s rows across %s '
             'distinct posts. Checks: %s checked, %s check failed, %s no check — and '
             'nothing may be counted without splitting on that column.\n'
             % (span([r['fy'] for r in personnel])[0], format(len(personnel), ','),
                len(by_post), checks['checked'], checks['check failed'],
                checks['no check']))
    t.append('\n| board, committee or post | years listed | how it is filled | states its size |\n'
             '|---|---|---|---|\n')
    for post in sorted(by_post):
        rs = by_post[post]
        sp, _n = span([r['fy'] for r in rs])
        kind = collections.Counter('%s %s' % (r['section'], r['kind']) for r in rs)
        stated = next((r['stated_members'] for r in rs if r['stated_members']), '')
        t.append('| %s | %s | %s | %s |\n'
                 % (post, sp, kind.most_common(1)[0][0], stated or 'no'))

    # ---- staffing and rosters -------------------------------------------------------
    t.append('\n## Staffing, where a department states it\n\n'
             '| department | years | how it states it |\n|---|---|---|\n')
    by_dept = collections.defaultdict(list)
    for r in staffing:
        by_dept[r['department']].append(r)
    for dept in sorted(by_dept):
        rs = by_dept[dept]
        sp, _n = span([r['fy'] for r in rs])
        kinds = sorted({r['measure'] for r in rs if r['measure']}) or ['prose, not counted']
        t.append('| %s | %s | %s |\n' % (dept, sp, '; '.join(kinds)))

    t.append('\n## Named rosters\n\n'
             '| department | years | names | agrees with the stated strength |\n'
             '|---|---|---:|---|\n')
    rc = collections.Counter((r['fy'], r['department']) for r in rosters)
    agree = {(r['fy'], r['department']): r['roster_check'] for r in rosters}
    for dept in sorted({d for _f, d in rc}):
        years = [f for f, d in rc if d == dept]
        sp, _n = span(years)
        ok = sum(1 for f in years if agree.get((f, dept)) == 'checked')
        t.append('| %s | %s | %s | %s of %s years |\n'
                 % (dept, sp, sum(n for (f, d), n in rc.items() if d == dept), ok,
                    len(years)))

    t.append('\n## What is missing, and from whom\n\n'
             '- **FY2011–FY2015 posts.** Ours. Those reports print the listing in a layout '
             'that states no membership anywhere, so the check that makes it readable does '
             'not exist in them and the reader refuses rather than guesses.\n'
             '- **Department detail for FY2026.** The town’s. Article 10 is printed as '
             'prose and no department figures appear in any form.\n'
             '- **Headcount for every department except Police, Fire and the schools.** '
             'The town’s, but only partly: departments describe their staffing in prose, '
             'in whichever form that year’s department head chose — a count, a range, an '
             'establishment post by post, a list of names. Those are different quantities '
             'and none of them is FTE.\n'
             '- **Which fund pays which post.** The town’s, and nothing published closes '
             'it. See `sources/data/money-gaps.csv`.\n')
    return ''.join(t)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    want = build()
    if a.check:
        cur = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        if cur != want:
            print('STALE %s' % os.path.relpath(OUT, ROOT), file=sys.stderr)
            return 1
        print('%s is current' % os.path.relpath(OUT, ROOT))
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, 'w', encoding='utf-8').write(want)
    print('wrote %s (%d lines)' % (os.path.relpath(OUT, ROOT), want.count('\n')))
    return 0


if __name__ == '__main__':
    sys.exit(main())
