#!/usr/bin/env python3
"""THE GATE: no document is ever deleted, cleaned or reset over while it is unbacked.

    python3 scripts/check_archive_backed_up.py            # is every held document safe?
    python3 scripts/check_archive_backed_up.py --push     # ...and back up whatever is not

Exit 0 means every publisher document this tree holds is recorded in the bucket, verified
by read-back. Exit 1 means at least one is not, and NOTHING DESTRUCTIVE MAY RUN.

TJ, 25 September 2026: *"i want to make sure any file we downoad is ALWAYS saved before we
can even think of deleting it or cleaning a repo..."*

WHY A GATE RATHER THAN A COMMENT. The refresh already backed things up -- at the END of its
run, and with the failure ignored (`check=False` in refresh.py), which means a run that died
before its last step left documents in exactly one place and said nothing. Six agendas were
in that state when this was written: fetched 25-30 September, present in one gitignored
directory on one machine, in no bucket and in no other tree.

    The archive's promise is that a document somebody published is kept forever.
    A document held on one disk is not kept. It is merely not lost yet.

WHAT IT CHECKS, AND WHY EACH SIDE IS NEEDED.

  * HELD AND UNBACKED -- a document on this disk with no verified push. This is the one
    that matters: the bytes exist once. Anything that deletes, cleans or resets must be
    blocked until this is empty.
  * INDEXED AND UNBACKED -- a document the manifest names, which nothing has pushed and
    this tree does not hold. It cannot be repaired from here, and it is worse than the
    first: there is no copy to push. It is reported separately and loudly, because the
    remedy is to find the tree that still holds it before that tree is cleaned.

WHAT IT DELIBERATELY DOES NOT DO. It does not ask the bucket. `archive-push-state.csv`
records a push that was READ BACK and compared, so it is already evidence rather than
hope -- and a gate that needs the network is a gate that fails on a bad morning and blocks
a refresh for the wrong reason. `check_archive_storage.py` is the one that reconciles
against the bucket itself; this one answers "is it safe to destroy anything" offline, in
under a second.

AND IT IS SCOPED TO FROZEN KEYS, per `archive_storage.frozen()` -- the publishers' own
files, which cannot be recovered by rebuilding anything. Our derived outputs are
regenerated by their generators and are not the archive's promise.
"""
import argparse
import csv
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import archive_storage as A  # noqa: E402

ROOT = os.path.dirname(HERE)
PUSH_STATE = os.path.join(ROOT, 'sources', 'data', 'archive-push-state.csv')


def pushed_keys():
    """Every key a push verified by reading it back out of the bucket."""
    if not os.path.exists(PUSH_STATE):
        return set()
    with open(PUSH_STATE, encoding='utf-8') as fh:
        return {r['key'] for r in csv.DictReader(fh) if r.get('key')}


def manifest_keys():
    if not os.path.exists(A.MANIFEST):
        return set()
    with open(A.MANIFEST, encoding='utf-8') as fh:
        return {r['key'] for r in csv.DictReader(fh) if r.get('key')}


def audit():
    """(held_unbacked, indexed_unbacked) -- both lists of frozen keys."""
    safe = pushed_keys()
    held = {k for k in A.walk_sources() if A.frozen(k)}
    indexed = {k for k in manifest_keys() if A.frozen(k)}
    held_unbacked = sorted(held - safe)
    indexed_unbacked = sorted((indexed - safe) - held)
    return held_unbacked, indexed_unbacked


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--push', action='store_true',
                    help='back up whatever is unbacked, then re-check')
    ap.add_argument('--quiet', action='store_true')
    a = ap.parse_args()

    held, indexed = audit()
    if a.push and held:
        print('%d document(s) held and unbacked -- pushing before anything else' % len(held))
        subprocess.run([sys.executable, os.path.join(HERE, 'sync_archive.py'),
                        '--push', '--frozen'], cwd=ROOT, check=False)
        held, indexed = audit()

    if held:
        print('%d DOCUMENT(S) HELD ON THIS DISK AND NOWHERE ELSE:' % len(held))
        for k in held[:20]:
            print('   ', k)
        if len(held) > 20:
            print('    ... and %d more' % (len(held) - 20))
        print('  Run: python3 scripts/sync_archive.py --push --frozen')
    if indexed:
        print('%d DOCUMENT(S) THE INDEX NAMES THAT NOTHING HAS PUSHED, and this tree does '
              'not hold:' % len(indexed))
        for k in indexed[:20]:
            print('   ', k)
        print('  These cannot be repaired from here. Find the tree that still holds them '
              'BEFORE it is cleaned; `git worktree list` is where to start.')
    if not held and not indexed and not a.quiet:
        n = len([k for k in A.walk_sources() if A.frozen(k)])
        print('ok: all %d document(s) this tree holds are in the bucket, read back and '
              'compared. Safe to clean.' % n)
    return 1 if (held or indexed) else 0


if __name__ == '__main__':
    sys.exit(main())
