#!/usr/bin/env python3
"""Is every generated file still what its generator would produce?

    python3 scripts/check_generated.py

THE ROOT CAUSE THIS EXISTS FOR

Nearly every defect found in this project on 5 September 2026 was one shape:
**something derived was written down, the thing it derived from moved, and nothing
connected the two.** Thirteen instances in a day.

  * a word index moved folders and llms.txt kept citing the old URL
  * a provenance join hardcoded `town-budget/index.csv` and resolved 0 of 225 rows
  * eight scripts globbed `town-budget/docs` for reports that had left it
  * 43 document rows named files that no longer existed, and were still being cited as
    the place to check a figure
  * a caveat quoted a series -- 0, 5, 4, 4, 0 -- typed from a field that the same commit
    had already fixed, so it repeated the undercount it existed to explain

Three sub-causes, and each has a countermeasure:

  1. **A LOCATION WAS HARDCODED where location is not identity.** This archive is keyed on
     provenance and re-files documents on purpose; a literal folder path in a script is a
     latent break with a date on it. Read the manifest or glob every `sources/*/index.csv`.
  2. **A FIGURE OR A NAME WAS TYPED into prose.** Rule 2 was stated for the projection and
     never applied to llms.txt, the READMEs, the caveats, the worked examples or the check
     fixtures -- all of which are prose that ships.
  3. **A JOIN THAT MATCHES NOTHING LOOKS EXACTLY LIKE DATA THAT IS ABSENT.** Four of the
     thirteen were silent zeros. A join whose result is used must assert that it matched.

This runs the `--check` mode of every generator, which is the mechanical half of the
answer: if an input moved, the output no longer reproduces, and this says so. It does not
catch a figure typed into a sentence that nothing regenerates -- for that the only defence
is deriving it, which is why the caveats and examples now are.
"""
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Every generator that can check itself. Ordered cheapest first, so a fast failure comes
# back fast. `sync_d1` is last because it is the only one that touches the network.
CHECKS = [
    ('build_readme.py', ['--check']),
    # Added 6 Sept 2026, after it had already drifted: two analyses were published
    # and /reports went on listing thirteen. Nothing caught it because this file is
    # the thing that catches it, and this generator was not in it.
    ('build_reports_index.py', ['--check']),
    ('build_money_flow.py', ['--check']),
    ('build_money_nodes.py', ['--check']),
    ('build_ledger_structure.py', ['--check']),
    ('build_who_decides.py', ['--check']),
    ('build_town_flow.py', ['--check']),
    # The schema inventory. It RUNS its worked queries against the live database, so this
    # entry also catches a query that has stopped answering -- not only a stale file.
    ('build_schema_page.py', ['--check']),
    # The reference pages, published into fy28/public/reference/ as byte-identical copies.
    # This entry is the whole reason that is safe: the originals are regenerated by the
    # scripts around it, so without a check the published copy is a snapshot of whatever
    # the page said on the day somebody ran the copier -- the exact shape of defect this
    # file exists for, with the added twist that a stale copy of a generated page is
    # indistinguishable from a current one. It also fails if a reference document appears
    # that is neither published nor deliberately excluded, which is the omission half.
    ('build_reference_pages.py', ['--check']),
    # Added 7 Sept 2026 after it had been CRASHING for an unknown length of time. It reads
    # a row's label as `label`; this schedule builds rows with `fund`, so every run raised
    # KeyError and the committed CSV could not be regenerated. It was not in this list,
    # which is the file whose whole job is catching that.
    ('extract_special_revenue.py', ['--check']),
    # The read-from-the-page version, checked against the report's own printed GRAND TOTAL
    # and against the identity the table states. Two independent checks; a year that does
    # not pass both is not in the dataset.
    ('verify_special_revenue_read.py', []),
    # The combined balance sheet, read from the page. Its cross-check is the strongest in
    # the archive: special revenue + enterprise fund equity must equal the special revenue
    # schedule's own carried-forward total — two documents, different pages, and the
    # second was verified to the penny by an entirely separate pass.
    ('verify_balance_sheet.py', []),
    # What the reports contain that we have not read, or have read without checking.
    # Generated because a count nobody maintains is the only kind that stays true.
    ('build_extraction_gaps.py', ['--check']),
    # The budget-versus-actual page's series. It reconciles every function group against
    # `variance_by_group` before it will write, so this entry catches two different things
    # going stale: the published file, and the agreement between the database route and
    # the CSV route to the same figure.
    ('build_variance_charts.py', ['--check']),
    # The school-staffing page's series. It reconciles two independent routes to the
    # paraprofessional dollars -- summing five line keys out of `budget_figure`, and
    # `sped_para_history`'s own total column -- and REFUSES to write if they share no year,
    # because a comparison that compares nothing passes trivially. It also refuses if the
    # roster fails to join to its classification, since a name with no category looks
    # exactly like a name with no role.
    ('build_staffing_charts.py', ['--check']),
    # The health-insurance page's series. Three things go stale independently here and this
    # catches all three: the published file against the ledger; the annual-report extract,
    # which refuses to write unless the insurance block of each year sums to the `Total
    # Insurance` that same page prints; and the gap-register rows the page quotes BY KEY,
    # since a limit whose reason has been renamed out from under it renders as an empty box.
    # It also refuses if a dept-914 account appears that this project has not described --
    # an undescribed account would otherwise be drawn as a bar with no meaning on it.
    ('build_insurance_charts.py', ['--check']),
    # The athletics page's series. Athletics is the one programme where both sides of the
    # money are visible, so this generator is also the place four assertions live that
    # nothing else in the project can make: the district workbook's cost columns summing
    # to its own printed total, the fund's cash chaining to the opening balance the town
    # printed for the next year, and -- the one that has actually gone wrong here -- a
    # REVENUE row reaching a spending total. An appropriation, a fund's spending and a
    # fund's receipts are three quantities, and "$335,856 through the revolving fund" was
    # once the second plus the third.
    ('build_athletics_charts.py', ['--check']),
    # The state-aid page's series. This one reaches outside the database for three of its
    # five quantities, so it is the entry that catches the most kinds of drift: the DESE
    # Chapter 70 workbook (whose column headings and Lunenburg row it asserts against
    # `model/taxbase.CH70` — two routes to the same eight figures), `model/finance.py`'s
    # state aid growth rate and FY27 revenue base, and five MEETING MINUTES, each quote
    # checked to still be present verbatim in the file it is attributed to. A quote that
    # has drifted from its source is rule 13's exact shape and nothing else here would see
    # it. It also refuses on a 45xx revenue object this project has not classified, since
    # `object LIKE '45%'` is neither all state aid nor only state aid — two of those
    # accounts are local option taxes the state merely collects.
    ('build_state_aid.py', ['--check']),
    # The free-cash page's series. It is the only generator here that reads FOUR
    # independent things and reconciles them against each other, so it catches the most
    # kinds of drift at once: the Division of Local Services' free cash proof (whose
    # eleven component rows must sum, to the cent, to the workbook's own `Identified Free
    # Cash July 1,` in all 45 town-years, and whose certified figure must chain year to
    # year); the WORKBOOK ITSELF, re-opened so every cited cell is asserted to hold the
    # cited amount — `source_ref` names the LABEL cell in column A and the amount is in
    # the year's own column, which is rule 13's exact shape; the TOWN's own undesignated
    # fund balance roll-forward out of two annual reports, cross-footed against both
    # totals each page prints and chained across the two documents, read from two
    # different instruments (OCR for FY2024, the PDF's text layer for FY2025); and five
    # figures `model/freecash.py` carries as TYPED constants, recomputed from the proof
    # they were copied out of. It also refuses on a `money_gaps` row it quotes by key
    # having been renamed, on a gap row whose stated figures have drifted from the data,
    # and on any of six meeting quotes no longer being present verbatim in the file it
    # is attributed to.
    ('build_free_cash_charts.py', ['--check']),
    # The special-revenue page's series. It re-derives the two checks that make the
    # dataset publishable rather than trusting the provenance note: every fund row's
    # forward + receipts − disbursements = carried, and every year's four columns
    # summed against the GRAND TOTAL the town printed. It refuses to write if either
    # fails or if the reconciliation join matches nothing, so this entry catches the
    # published file going stale AND a rebuild that silently emptied the table.
    ('build_special_revenue.py', ['--check']),
    # How far the money can be followed — the six rungs on /what-we-cannot-answer. It
    # quotes each rung's reason out of `money_gaps` and `money_edges` BY KEY and exits if
    # a key is not there, so this entry catches two things: the published file going
    # stale against the ledger, and a gap-register row being renamed out from under a
    # rung that would otherwise render with no reason on it.
    ('build_traceability_ladder.py', ['--check']),
    ('build_sitemap.py', ['--check']),
    ('check_github_mirror.py', []),
    ('classify_roster_roles.py', ['--check']),
    ('build_views.py', ['--check']),
    ('build_archive_guide.py', ['--check']),
    ('build_show_your_work.py', ['--check']),
    ('build_data_model_grids.py', ['--check']),
    ('split_large_text.py', ['--check']),
    ('build_question_bank.py', ['--check']),
    ('build_db.py', ['--check']),
    ('check_archive_layout.py', []),
    ('check_moved_docs.py', []),
    ('build_source_index.py', []),
    ('sync_d1.py', ['--check']),
]


def main():
    failed = []
    for script, args in CHECKS:
        path = os.path.join(ROOT, 'scripts', script)
        if not os.path.exists(path):
            continue
        label = script + (' ' + ' '.join(args) if args else '')
        r = subprocess.run([sys.executable, path, *args], cwd=ROOT,
                           capture_output=True, text=True)
        mark = ' ok ' if r.returncode == 0 else 'FAIL'
        tail = (r.stdout or r.stderr).strip().splitlines()
        print(f'  {mark}  {label:42s} {tail[-1][:60] if tail else ""}')
        if r.returncode != 0:
            failed.append((label, (r.stdout or r.stderr).strip()))

    print()
    if failed:
        print(f'{len(failed)} generator(s) no longer reproduce their output:\n')
        for label, out in failed:
            print(f'--- {label}')
            print('\n'.join(out.splitlines()[-6:]))
            print()
        print('Something a generated file depends on has moved or changed. That is the '
              'shape\nof nearly every defect in this project: a derived thing written '
              'down, and the\nthing it derived from moved underneath it.')
        return 1
    print(f'ok: all {len(CHECKS)} generators still reproduce what is committed')
    return 0


if __name__ == '__main__':
    sys.exit(main())
