#!/usr/bin/env python3
"""The page of the appropriations schedule that the generic extract never saw.

    python3 scripts/extract_appropriations_supplement.py
    python3 scripts/extract_appropriations_supplement.py --check

Writes `sources/data/report-appropriations-supplement.csv` and
`sources/data/report-appropriations-supplement-refused.csv`.

--------------------------------------------------------------------------------------
WHY THERE IS A SUPPLEMENT AT ALL
--------------------------------------------------------------------------------------

`report-appropriations.csv` holds FY2011 pages 61 to 65 and does not hold page 60, which
is page ONE of the same table: `TOWN OF LUNENBURG / GENERAL FUND APPROPRIATIONS / SUMMARY
& CLASSIFICATION OF ACCOUNT / FISCAL YEAR 2011`, from GENERAL GOVERNMENT down to the
Treasurer's banking charges.

It is missing because the fixed-width page cache the generic extractor reads renders
three figures for that page where Apple Vision returns 127. Rule 13c: that is a statement
about our instrument. The town printed the page.

**And the cost of it is visible in the dataset's own reconciliation.** Every FY2011 row
in `report-appropriations.csv` carries `status = check failed` and a note that begins

    appropriated: 26,433,400.67 vs 27,948,061.40 (-1,514,660.73)

-- the schedule's own printed grand total against what the rows beneath it add up to.
A missing first page is exactly the shape of a shortfall like that. This script does not
assert that page 60 closes it: it reads the page, publishes what proves, and prints the
column sums so anybody can put the two side by side. Rule 7 -- the measurement is the
measurement, and "this is why the total was short" is a hypothesis until the numbers are
laid next to each other.

The supplement is a COMPANION, not a replacement. It does not touch
`report-appropriations.csv`, which is generated by `extract_tables.py` and shared, and it
carries the same grain -- one row per printed line -- under its own column names.

--------------------------------------------------------------------------------------
WHAT PROVES A ROW
--------------------------------------------------------------------------------------

The schedule states one identity, over and over, and prints nothing else that adds up:

    the lines of a program  =  the program's subtotal,  in every column it prints

The subtotal is the row with figures and NO LABEL -- that is how this table prints it,
and it is what separates a program's total from its lines without needing to know any
program's name. A program is published only where that closes to the cent in every column
the subtotal prints; where it does not, the program's lines go to the refusal file with
the difference, and are not published at all.

Worked, from the top of the page, so the identity is not taken on trust:

    Payroll-Administration        $100,884.72   $100,884.72   $101,984.97
    Selectmen's Salaries              $500.00       $500.00       $500.00
    Other Expenses                  $5,000.00     $5,000.00     $3,899.75
    (no label)                    $106,384.72   $106,384.72   $106,384.72   $0.00   $0.00

100,884.72 + 500.00 + 5,000.00 = 106,384.72 in the appropriated column, and
101,984.97 + 500.00 + 3,899.75 = 106,384.72 in the expended column. Two different sets of
figures, one printed total, both closing: a misread digit cannot do that twice.

--------------------------------------------------------------------------------------
READING THE PAGE -- rule 13b, in order
--------------------------------------------------------------------------------------

1. **MEASURE the rotation.** The median slope from each figure to its nearest neighbour
   to the right, then `Y = y - slope*x`. Not a tolerance.
2. **The band is half the page's OWN row pitch**, measured on the deskewed rows.
3. **Figures are placed by their RIGHT EDGE**, because accounting figures are
   right-aligned and the `$` on some rows and not others moves both the left edge and the
   centre. A figure further than half the column pitch from every heading is dropped
   rather than pushed into the nearest one.
4. **The columns are NAMED from the header that is printed on the page** --
   `APPROPRIATED / FORWARD`, `TOTAL FUNDS AVAILABLE`, `TOTAL EXPENDED`,
   `TOTAL ENCUMBERED`, `BALANCE TO REVENUE`. Not from their order, and not from what the
   figures look like.

--------------------------------------------------------------------------------------
FY2017 PAGE 155 IS NOT READ HERE, AND THAT IS THE RIGHT ANSWER
--------------------------------------------------------------------------------------

The other page the catalogue leaves unread under `appropriations` is FY2017 page 155,
which prints the FY'18 omnibus budget INTERLEAVED -- two columns of the schedule side by
side, account numbers 1, 2, 3, 3A, 3B in the left half and 10, 13, 13A, 14A in the right,
so a row band holds two unrelated lines. It looks like a page nobody has read.

It has been read, on the sheet where the town prints it straight. Checked, not assumed:
page 155 prints `Principal-Loans  $3,102,790.88` and `Group Health Insurance
$2,071,625.52`, and `report-appropriations.csv` already holds both, at FY2017 page 168,
as `1 Principal-Loans` and `6 Group Health Insurance`. Reading the interleaved reprint
would add a second, worse copy of lines the archive already has straight. It is recorded
as a refusal with that evidence rather than read.
"""
import argparse
import collections
import csv
import io
import os
import re
import statistics
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OCR = os.path.join(ROOT, 'sources', 'town-budget', 'ocr')
MAIN = os.path.join(ROOT, 'sources', 'data', 'report-appropriations.csv')
OUT = os.path.join(ROOT, 'sources', 'data', 'report-appropriations-supplement.csv')
OUT_REFUSED = os.path.join(ROOT, 'sources', 'data',
                           'report-appropriations-supplement-refused.csv')

FIELDS = ['report_fy', 'document', 'page', 'program', 'line_no', 'label', 'kind',
          'appropriated_or_forward', 'total_funds_available', 'total_expended',
          'total_encumbered', 'balance_to_revenue', 'proof']
REFUSED_FIELDS = ['report_fy', 'document', 'page', 'subject', 'reason', 'evidence']

# report_fy, document, page -- the pages of an appropriations schedule that the generic
# extract does not hold. Checked against `report-appropriations.csv` at run time, so a
# page that starts being read there is reported rather than silently duplicated.
WANTED = [('2011', '4117-fy-2011-annual-town-report.pdf', 60)]

# THE COLUMNS, AS THE PAGE PRINTS THEM. The heading is set over two or three lines, so
# each column is found by the word that is unique to it and the others are ignored:
# `TOTAL` alone appears three times and names nothing.
COLUMNS = [('appropriated_or_forward', 'APPROPRIATED'),
           ('total_funds_available', 'AVAILABLE'),
           ('total_expended', 'EXPENDED'),
           ('total_encumbered', 'ENCUMBERED'),
           ('balance_to_revenue', 'REVENUE')]

MONEY = re.compile(r'^[\s$S]*(\(?)\s*([\d]{1,3}(?:[.,]\d{3})*[.,]\d\d)\s*(\)?)'
                   r'[\s.]*(?:fwd|srt|f\.?w\.?d|s\.?r\.?t)?[\s.]*$', re.I)
LETTERS = re.compile(r'[A-Za-z]{3}')


def money(text):
    """The figure a box holds, in dollars and cents, or None.

    The separator may be a comma or a full stop -- a scanner cannot tell them apart and
    the cache holds `$7.637.48` for $7,637.48 on this very page -- so the LAST one is the
    decimal point and any before it are group separators. `55,500.00` is the page's own
    `$5,500.00` with the dollar sign read as a five, and nothing here can know that; it
    fails the program's subtotal instead, which is the point of having one.
    """
    m = MONEY.match(text.strip())
    if not m:
        return None
    body = m.group(2)
    v = float(body[:-3].replace(',', '').replace('.', '') + '.' + body[-2:])
    return -v if m.group(1) and m.group(3) else v


def load(path, page):
    """Vision boxes for one page, y flipped to a top-left origin. Tabs, never csv."""
    out = []
    with open(path, encoding='utf-8', errors='replace') as fh:
        for i, line in enumerate(fh):
            f = line.rstrip('\n').split('\t')
            if i == 0 or len(f) < 7:
                continue
            try:
                p, x, y, w, h = int(f[0]), float(f[1]), float(f[2]), float(f[3]), float(f[4])
            except ValueError:
                continue
            if p == page:
                out.append({'x': x, 'y': 1.0 - y - h, 'w': w, 'h': h,
                            'r': x + w, 'text': '\t'.join(f[6:]).strip()})
    return out


def deskew(boxes):
    """The page's own rotation, measured from the figures, never guessed."""
    figs = [b for b in boxes if money(b['text']) is not None]
    slopes = []
    for v in figs:
        right = [w for w in figs if 0.02 < w['x'] - v['x'] < 0.30]
        if not right:
            continue
        w = min(right, key=lambda w: abs(w['y'] - v['y']))
        if abs(w['y'] - v['y']) < 0.02:
            slopes.append((w['y'] - v['y']) / (w['x'] - v['x']))
    s = statistics.median(slopes) if len(slopes) >= 8 else 0.0
    return [dict(b, Y=b['y'] - s * b['x']) for b in boxes], s


def bands(boxes):
    """Rows, banded at half the page's own median pitch -- measured, not a constant."""
    ys = sorted({round(b['Y'], 4) for b in boxes})
    gaps = sorted(b - a for a, b in zip(ys, ys[1:]) if 0.003 < b - a < 0.06)
    band = (gaps[len(gaps) // 2] / 2.0) if gaps else 0.005
    rows = []
    for b in sorted(boxes, key=lambda b: (b['Y'], b['x'])):
        if rows and abs(b['Y'] - rows[-1][0]['Y']) < band:
            rows[-1].append(b)
        else:
            rows.append([b])
    for r in rows:
        r.sort(key=lambda b: b['x'])
    return rows, band


def rejoin(rows, band):
    """Put a label back on the figures it belongs to when the band split them.

    `Tax letor Arministration` -- the scanner's reading of Tax Collector Administration --
    is printed a hair BELOW the figures on its own line, three thousandths of a page where
    the band is four, so it lands in the next row down. The figures then arrive with no
    label at all and look exactly like a program's subtotal, which closed the program
    above them early and cost three programs on this page.

    A row of figures with no label, sitting next to a row of label with no figures, is one
    printed line. This is not a tolerance being widened: the band stays measured, and only
    the two halves that cannot each be a row on their own are put back together.
    """
    out = list(rows)
    for i, r in enumerate(out):
        if any(money(b['text']) is not None for b in r):
            continue
        if not any(LETTERS.search(b['text']) and b['r'] < 0.35 for b in r):
            continue
        for j in (i - 1, i + 1):
            if not 0 <= j < len(out) or not out[j]:
                continue
            if abs(out[j][0]['Y'] - r[0]['Y']) > band * 1.5:
                continue
            figs = [b for b in out[j] if money(b['text']) is not None]
            if len(figs) >= 2 and not any(LETTERS.search(b['text']) and b['r'] < 0.35
                                          for b in out[j]):
                out[j] = sorted(out[j] + r, key=lambda b: b['x'])
                out[i] = []
                break
    return [r for r in out if r]


def header(rows):
    """Column right edges, named off the words the page prints over them."""
    cols = {}
    for r in rows[:12]:
        for b in r:
            t = b['text'].upper()
            for name, word in COLUMNS:
                if word in t and name not in cols:
                    cols[name] = b['r']
    return cols


def place(figs, cols, pitch):
    """Each figure under the heading its RIGHT EDGE is nearest, or under none."""
    out = {}
    for f in figs:
        name, d = min(((n, abs(r - f['r'])) for n, r in cols.items()), key=lambda t: t[1])
        if d > pitch * 0.5:
            continue
        out.setdefault(name, []).append(f)
    return {k: v[0] for k, v in out.items() if len(v) == 1}


def read_page(fy, doc, page, refused):
    path = os.path.join(OCR, doc[:-4] + '.tsv')
    boxes = load(path, page)
    if not boxes:
        refused.append({'report_fy': fy, 'document': doc, 'page': page,
                        'subject': 'appropriations',
                        'reason': 'the page has no Vision reading in the archive',
                        'evidence': 'expected %s' % os.path.relpath(path, ROOT)})
        return []
    boxes, slope = deskew(boxes)
    rows, band = bands(boxes)
    rows = rejoin(rows, band)
    cols = header(rows)
    if len(cols) < 3:
        refused.append({'report_fy': fy, 'document': doc, 'page': page,
                        'subject': 'appropriations',
                        'reason': 'the column header could not be read off the page',
                        'evidence': 'found %s' % (sorted(cols) or 'nothing')})
        return []
    edges = sorted(cols.values())
    pitch = statistics.median([b - a for a, b in zip(edges, edges[1:])])

    # Walk the page. A program is named by a label row with no figure on it; its lines
    # accumulate; the row with figures and NO label closes it.
    out, pending, program, line_no, named, orphan = [], [], '', 0, False, ''
    closed = openblocks = 0
    for r in rows:
        figs = [b for b in r if money(b['text']) is not None]
        labels = [b for b in r if b['r'] < 0.35 and LETTERS.search(b['text'])
                  and money(b['text']) is None]
        label = re.sub(r'\s+', ' ', ' '.join(b['text'] for b in labels)).strip(' .:')
        cells = place(figs, cols, pitch)
        if not cells:
            if label and len(label) > 3 and not label.upper().startswith('TOWN OF'):
                program, named = label, True
                orphan = label
            continue
        row = {k: money(v['text']) for k, v in cells.items()}
        # A SUBTOTAL FILLS THE ROW; A CARRY-FORWARD NOTE DOES NOT. The page prints
        # `$156.47 fwd` and `$106.98 fwd` on a line of their own, in the appropriated
        # column and nowhere else -- money brought forward into the program below. Both
        # are unlabelled, so "no label means subtotal" made each of them close a block
        # early and threw away the three programs underneath. A subtotal prints in at
        # least two of the five columns; a forward note prints in one. And the money is
        # not discarded: it is a line of its own program, and it is what makes the
        # Tax Collector's Administration close -- 156.47 + 30,119.00 + 27,959.92 +
        # 14,433.28 = 72,668.67, the subtotal printed four rows further down.
        # A LABEL THE BANDING PUT ON ITS OWN ROW. `Tax letor Arministration` -- the
        # scanner's reading of Tax Collector Administration -- sits three thousandths of a
        # page above the figures that belong to it, and the band is four. So the figures
        # arrive unlabelled and look exactly like a subtotal, which closed the program
        # above them early and lost three programs. A label-only row IMMEDIATELY followed
        # by an unlabelled figure row is that label's own line: a real subtotal never has
        # a bare program name sitting directly on top of it, because a program's lines
        # come in between.
        if not label and orphan and not any(q['label'] for q in pending):
            label, orphan = orphan, ''
        if not label and len(row) < 2:
            line_no += 1
            pending.append({'label': '', 'row': row, 'line_no': line_no})
            continue
        if label:
            line_no += 1
            if not named:
                program = label
                named = True
            pending.append({'label': label, 'row': row, 'line_no': line_no})
            continue
        # A SUBTOTAL. Test it against the lines standing above it, column by column --
        # but only in the columns the LINES print. `TOTAL ENCUMBERED` and `BALANCE TO
        # REVENUE` are struck once per program, on the subtotal row, and nowhere on the
        # lines; asking them to foot is asking a figure to equal the sum of nothing, and
        # it refused every program on the page. They are published as printed and
        # `proof` says they were not tested, rather than being quietly counted as passing.
        checked, failed, untested, fatal = [], [], [], []
        for name, _ in COLUMNS:
            if name not in row:
                continue
            if not any(name in p['row'] for p in pending):
                untested.append(name)
                continue
            got = sum(p['row'].get(name, 0.0) for p in pending)
            (checked if abs(got - row[name]) < 0.005 else failed).append(
                '%s %s vs %s' % (name, format(got, ',.2f'), format(row[name], ',.2f')))

        # A SECOND IDENTITY, AND THE REASON IT IS HERE. The column sum has no power to
        # fail on a program with ONE line, because the subtotal is that line repeated --
        # and rule 13 is explicit that a check with no power to fail is worse than no
        # check. The row states another one, in the words of its own headings:
        #
        #     TOTAL FUNDS AVAILABLE - TOTAL EXPENDED - TOTAL ENCUMBERED
        #                                            = BALANCE TO REVENUE
        #
        # Zoning Board of Appeals: 3,328.00 - 1,684.36 - 98.87 = 1,544.77, printed.
        # It holds across the page and it tests a one-line program as hard as a four-line
        # one.
        a, e, n, bal = (row.get('total_funds_available'), row.get('total_expended'),
                        row.get('total_encumbered') or 0.0,
                        row.get('balance_to_revenue'))
        if a is not None and e is not None and bal is not None:
            (checked if abs(a - e - n - bal) < 0.005 else failed).append(
                'available - expended - encumbered %s vs balance to revenue %s'
                % (format(a - e - n, ',.2f'), format(bal, ',.2f')))

        # THE CURRENCY SIGN READ AS A DIGIT, which is the misread this table invites.
        # Tax Title & Takings prints `$5,500.00` in both money columns and Vision returns
        # `55,500.00` in the first -- on the line AND on the subtotal, so the column sum
        # closes perfectly on a figure ten times too large. That is a compensating error,
        # and the only thing that catches it is the magnitude: an appropriation is not ten
        # times the funds it made available. The whole program is refused rather than
        # published with one impossible column.
        for p_ in pending + [{'row': row, 'label': ''}]:
            ap, av = (p_['row'].get('appropriated_or_forward'),
                      p_['row'].get('total_funds_available'))
            if ap and av and av > 0 and ap > 5 * av:
                fatal.append('appropriated %s is more than five times the funds '
                              'available %s on one line -- a currency sign read as a '
                              'digit' % (format(ap, ',.2f'), format(av, ',.2f')))
        failed += fatal
        if pending and checked and not failed:
            closed += 1
            proof = 'the lines above sum to this subtotal in %d column(s): %s' \
                    % (len(checked), '; '.join(checked))
            if untested:
                proof += ' -- printed only on the subtotal, so untested: %s' \
                         % ', '.join(untested)
            for p in pending:
                out.append(dict(report_fy=fy, document=doc, page=page, program=program,
                                line_no=p['line_no'], label=p['label'], kind='line',
                                proof=proof,
                                **{n: ('%.2f' % p['row'][n]) if n in p['row'] else ''
                                   for n, _ in COLUMNS}))
            out.append(dict(report_fy=fy, document=doc, page=page, program=program,
                            line_no='', label='', kind='subtotal', proof=proof,
                            **{n: ('%.2f' % row[n]) if n in row else ''
                               for n, _ in COLUMNS}))
        elif pending and not fatal and 'total_encumbered' not in row \
                and 'balance_to_revenue' not in row:
            # NOT EVERY UNLABELLED ROW OF FIGURES IS A SUBTOTAL. Tax Collector
            # Administration's first line is `$30,119.00 $30,119.00 $30,119.40` and its
            # LABEL was never recognised at all -- Vision read the program's name two
            # lines up as `Tax letor Arministration` and the line's own name not at all.
            # Taken as a subtotal it fails, 156.47 against 30,119.00, and takes three
            # programs down with it. Taken as a line it closes the program four rows
            # later: 156.47 + 30,119.00 + 27,959.92 + 14,433.28 = 72,668.67, printed.
            #
            # So where the identity fails AND the row prints nothing in the two columns
            # that only a subtotal carries, it is read as a line and the walk continues.
            # The DOCUMENT decides, exactly as it does for the debt schedule's shifted
            # pages -- and a row put in the wrong place cannot make a later subtotal close
            # instead, which is what makes trying it safe.
            line_no += 1
            pending.append({'label': '', 'row': row, 'line_no': line_no})
            continue
        elif pending:
            openblocks += 1
            refused.append({'report_fy': fy, 'document': doc, 'page': page,
                            'subject': 'appropriations',
                            'reason': 'a program\'s lines do not sum to the subtotal '
                                      'printed beneath them, so none of them is published',
                            'evidence': '%s: %s' % (program or 'unnamed program',
                                                    '; '.join(failed) or 'no column '
                                                    'in common with the lines')})
        pending, line_no, named, orphan = [], 0, False, ''
    if pending:
        refused.append({'report_fy': fy, 'document': doc, 'page': page,
                        'subject': 'appropriations',
                        'reason': 'lines at the foot of the page sit beneath no printed '
                                  'subtotal, so nothing in the document tests them',
                        'evidence': '%d line(s) after %s'
                                    % (len(pending), program or 'the last program named')})
    print('  FY%s page %d: rotation %+.5f, %d programs close, %d refused'
          % (fy, page, slope, closed, openblocks))
    return out


def already_read(fy, page):
    if not os.path.exists(MAIN):
        return False
    with open(MAIN, encoding='utf-8') as fh:
        return any(r['fy'] == fy and r['page'] == str(page) for r in csv.DictReader(fh))


def write(path, fields, rows, check):
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=fields, lineterminator='\n')
    w.writeheader()
    w.writerows(rows)
    if check:
        cur = open(path, encoding='utf-8', newline='').read() if os.path.exists(path) else ''
        if cur != buf.getvalue():
            print('  STALE: %s -- run python3 '
                  'scripts/extract_appropriations_supplement.py'
                  % os.path.relpath(path, ROOT))
            return 1
        print('  %s is current' % os.path.relpath(path, ROOT))
        return 0
    open(path, 'w', encoding='utf-8', newline='').write(buf.getvalue())
    print('wrote %s (%d rows)' % (os.path.relpath(path, ROOT), len(rows)))
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()

    rows, refused = [], []
    for fy, doc, page in WANTED:
        if already_read(fy, page):
            refused.append({'report_fy': fy, 'document': doc, 'page': page,
                            'subject': 'appropriations',
                            'reason': 'report-appropriations.csv now holds this page; '
                                      'take it out of WANTED rather than reading it twice',
                            'evidence': 'the generic extract has rows for FY%s page %d'
                                        % (fy, page)})
            continue
        rows += read_page(fy, doc, page, refused)

    # FY2017 page 155 -- recorded, with the evidence, rather than read. See the docstring.
    refused.append({
        'report_fy': '2017', 'document': '4124-fy-2017-annual-town-report.pdf',
        'page': 155, 'subject': 'appropriations',
        'reason': 'the page reprints the FY\'18 omnibus budget INTERLEAVED, two columns '
                  'of the schedule side by side, and every line on it is already held '
                  'from the sheet where the town prints it straight',
        'evidence': 'page 155 prints `Principal-Loans 3,102,790.88` and `Group Health '
                    'Insurance 2,071,625.52`; report-appropriations.csv holds both at '
                    'FY2017 page 168, as `1 Principal-Loans` and `6 Group Health '
                    'Insurance`'})

    refused.sort(key=lambda r: (r['report_fy'], int(r['page']), r['reason']))
    print('APPROPRIATIONS SUPPLEMENT: %d rows, %d pages, %d refusals'
          % (len(rows), len({(r['report_fy'], r['page']) for r in rows}), len(refused)))
    for name, _ in COLUMNS:
        tot = sum(float(r[name]) for r in rows if r['kind'] == 'subtotal' and r[name])
        print('  %-24s subtotals sum to %16s' % (name, format(tot, ',.2f')))
    for r in refused:
        print('  REFUSED FY%s page %s: %s' % (r['report_fy'], r['page'], r['reason']))

    rc = write(OUT, FIELDS, rows, a.check)
    rc |= write(OUT_REFUSED, REFUSED_FIELDS, refused, a.check)
    return rc


if __name__ == '__main__':
    sys.exit(main())
