#!/bin/bash
# Read the votes out of the town's own minutes, board by board, until there are none left.
#
#   nohup bash scripts/run_official_votes_backfill.sh > /tmp/official-votes.log 2>&1 &
#
# TJ, 22 September 2026: *"lets use some agentic process to push forward 'Votes, from the
# town's own minutes'"* -- and, on the cost: *"its ok do it. i know the cost."*
#
# WHAT IT COSTS, SAID ONCE. Every meeting is one `claude -p` call on the small model,
# about 0.03% of the plan's weekly allowance. 3,899 meetings are unread, so a complete
# sweep is a little over a WEEK's allowance. That is why this writes each meeting as it
# finishes and can be stopped at any moment without losing or repeating work: an
# already-read meeting is skipped, so a restart costs nothing.
#
# THE ORDER IS THE BUDGET BOARDS FIRST, then everything else by how much is unread.
# Newest-first inside a board, which the extractor already does. The reasoning is the one
# the transcript backfill learned: a backfill is not a refresh, and sweeping by recency
# across all boards reaches the meetings somebody already has minutes for. What is worth
# reaching first is the body that appropriates.
#
# DO NOT EDIT THIS FILE WHILE IT IS RUNNING -- bash reads a script lazily, by byte offset.
set -u
cd "$(dirname "$0")/.." || exit 1

BATCH=12        # meetings per board per pass, then move on so no board starves
PAUSE=5         # between launches
JOBS=2          # boards read AT ONCE

# WHY IT RUNS BOARDS IN PARALLEL. Measured 22 September 2026: one meeting takes 14
# seconds on a short set of minutes and just over two MINUTES on a Select Board set that
# yields seven votes -- at 8% CPU. The time is the model answering, not this machine
# working, so doing one board at a time leaves the box idle almost all of it.
#
# Boards are independent and each meeting writes its own file, so there is nothing to
# coordinate. Four at once is a deliberate ceiling rather than a maximum: every call
# spends the plan's shared allowance, and the same allowance is what an interactive
# session runs on.
FIRST="select-board finance-committee school-committee"

pass=0
while true; do
  pass=$((pass + 1))
  # Ask the extractor what is left, every pass: a board finished by an earlier pass drops
  # out on its own rather than being maintained in a list here.
  # macOS ships bash 3.2, which has no `mapfile`. A plain word list is enough here and
  # works on both; board slugs never contain spaces.
  LEFT=$(python3 scripts/extract_official_votes.py --status 2>/dev/null \
    | awk '{ if (NF>=4 && $2 ~ /^[0-9]+$/ && $4 ~ /^[0-9]+$/ && $2 < $4) print $4-$2, $1 }' \
    | sort -rn | awk '{print $2}')
  if [ -z "$LEFT" ]; then
    echo "$(date -u +%H:%M:%S)  nothing left to read — every board complete"
    break
  fi
  # The budget boards go first while they still have anything unread.
  ORDER=""
  for b in $FIRST; do
    for l in $LEFT; do [ "$l" = "$b" ] && ORDER="$ORDER $b"; done
  done
  for l in $LEFT; do
    case " $FIRST " in *" $l "*) ;; *) ORDER="$ORDER $l" ;; esac
  done
  n=$(echo "$LEFT" | wc -w | tr -d ' ')
  echo "$(date -u +%H:%M:%S)  pass $pass — $n board(s) with unread minutes"
  # bash 3.2 has no `wait -n`, so this runs in waves of $JOBS and waits for each wave.
  # Slightly less efficient than a rolling pool and enormously simpler to reason about.
  running=0
  for b in $ORDER; do
    echo "$(date -u +%H:%M:%S)  $b — up to $BATCH"
    python3 scripts/extract_official_votes.py --board "$b" --limit "$BATCH" 2>&1 \
      | sed "s/^/  [$b] /" &
    running=$((running + 1))
    sleep "$PAUSE"
    if [ "$running" -ge "$JOBS" ]; then
      wait
      running=0
    fi
  done
  wait
done
