#!/bin/bash
# Fetch every meeting transcript, slowly, for as long as it takes.
#
# THE CONSTRAINT IS YOUTUBE'S PATIENCE, NOT OURS. The caption endpoint throttles by IP --
# ten fetches in 35 seconds earned a 429 from two different libraries -- and a throttle
# that is being hammered may last longer than one that is being waited out. So this does
# the opposite of retrying hard: it fetches slowly, stops the moment it is refused three
# times, sleeps for a long while, and tries again.
#
# It costs no money and no model tokens. Nothing depends on it finishing today.
#
#   nohup bash scripts/run_transcript_backfill.sh > /tmp/transcripts.log 2>&1 &
set -u
# DO NOT EDIT THIS FILE WHILE IT IS RUNNING. bash reads a script lazily, by byte offset,
# so an in-place edit shifts the ground under a shell that is mid-loop and it can resume
# in the middle of a line. This was done once, on 10 September 2026, and got away with it
# only because the edit landed behind the read head. Stop the run, edit, restart -- the
# index is written after every fetch, so a restart costs nothing and re-fetches nothing.
cd "$(dirname "$0")/.."

BOARDS="school-committee select-board finance-committee"
BATCH=25          # per attempt, then a long pause regardless
SLEEP=45          # between individual fetches
COOLDOWN=1800     # first cooldown after a throttled batch; DOUBLES while it stays stuck
COOLDOWN_MAX=21600  # ...up to six hours
BETWEEN=300       # 5 min after a clean batch

# THE 231 DOCUMENT-LESS MEETINGS COME FIRST, and this ordering is the whole point.
# Newest-first is right for a refresh and wrong for a backfill: every meeting reached
# working backwards from today ALSO had minutes, so after fifty fetches the number of
# meetings made searchable that were not searchable before was NOUGHT. 226 recordings
# carry evidence `video only` in the register -- 158 of them School Committee -- and for
# those a rough caption is the difference between an account and none.
#
# It runs to completion before the boards loop, and it is idempotent: an already-fetched
# recording is skipped from the index, so re-running costs nothing.
echo "$(date -u +%H:%M:%S)  PHASE 1 — meetings with no surviving document"
while true; do
  left=$(python3 scripts/fetch_youtube_transcripts.py --video-only --status 2>/dev/null \
         | awk '/video\(s\) in scope/ {print $(NF-1)}')
  [ -z "${left:-}" ] && left=0
  [ "$left" -eq 0 ] && { echo "$(date -u +%H:%M:%S)  phase 1 complete"; break; }
  echo "$(date -u +%H:%M:%S)  video-only — $left remaining, taking $BATCH"
  # `left` was read a moment ago and is the same number; asking again costs a fork and a
  # second read of the index for nothing.
  before="$left"
  python3 scripts/fetch_youtube_transcripts.py --video-only \
      --limit "$BATCH" --sleep "$SLEEP" 2>&1 | tail -5
  after=$(python3 scripts/fetch_youtube_transcripts.py --video-only --status 2>/dev/null \
          | awk '/video\(s\) in scope/ {print $(NF-1)}')
  # A batch that moved nothing means the endpoint is refusing. Go away for a while
  # rather than grinding -- hammering a throttle makes the next run worse too.
  if [ "${after:-0}" -ge "${before:-0}" ]; then
    # ESCALATING BACKOFF. A fixed 30 minutes is right for a passing throttle and wrong
    # for a sustained block: on 10 September 2026 three consecutive cooldowns fetched
    # nothing at all, which means each retry was poking an endpoint that had already
    # refused and, by this script's own reasoning, making the block last longer. So the
    # wait DOUBLES for as long as nothing is landing, and resets the moment a batch
    # succeeds. Nothing depends on this finishing today.
    echo "$(date -u +%H:%M:%S)  no progress — cooling down ${COOLDOWN}s"
    sleep "$COOLDOWN"
    COOLDOWN=$(( COOLDOWN * 2 ))
    [ "$COOLDOWN" -gt "$COOLDOWN_MAX" ] && COOLDOWN=$COOLDOWN_MAX
  else
    COOLDOWN=1800
    sleep "$BETWEEN"
  fi
done

echo "$(date -u +%H:%M:%S)  PHASE 2 — everything else, newest first"
while true; do
  progressed=0
  for b in $BOARDS; do
    left=$(python3 scripts/fetch_youtube_transcripts.py --board "$b" --status 2>/dev/null \
           | awk '/video\(s\) in scope/ {print $(NF-1)}')
    [ -z "${left:-}" ] && left=0
    if [ "$left" -eq 0 ]; then
      echo "$(date -u +%H:%M:%S)  $b complete"
      continue
    fi
    echo "$(date -u +%H:%M:%S)  $b — $left remaining, taking $BATCH"
    if python3 scripts/fetch_youtube_transcripts.py --board "$b" \
         --limit "$BATCH" --sleep "$SLEEP" 2>&1 | tail -20 | grep -q "fetched"; then
      progressed=1
    fi
    # Did that batch actually land anything? A batch that fetched nothing means the
    # throttle is on, and the right response is to go away for a while.
    if python3 scripts/fetch_youtube_transcripts.py --board "$b" --status 2>/dev/null \
         | grep -q "0 fetched"; then
      echo "$(date -u +%H:%M:%S)  throttled — sleeping ${COOLDOWN}s"
      sleep "$COOLDOWN"
    else
      sleep "$BETWEEN"
    fi
  done
  remaining=$(python3 scripts/fetch_youtube_transcripts.py --status 2>/dev/null \
              | awk '/video\(s\) in scope/ {print $(NF-1)}')
  if [ "${remaining:-1}" = "0" ]; then
    echo "$(date -u +%H:%M:%S)  ALL BOARDS COMPLETE"; break
  fi
  [ "$progressed" -eq 0 ] && { echo "no progress this cycle; long sleep"; sleep "$COOLDOWN"; }
done
