"""Which unfinished annual-report pages carry their own TEXT, and which are photographs.

    python3 scripts/survey_text_layer.py
    python3 scripts/survey_text_layer.py --check

Writes `notes/generated/TEXT-LAYER-COVERAGE.md`.

WHY THIS EXISTS

`notes/process/READING-A-REPORT-PAGE.md` opens with a gate: where a page carries a text
layer it supersedes OCR and the OCR reading is discarded. The gate is only useful if you
know WHICH pages those are, and the honest answer was being guessed at.

IT IS A PROPERTY OF THE PAGE, NOT OF THE REPORT, and assuming otherwise cost a wrong
recommendation. FY2025 is born-digital throughout, so "eight of the sixteen reports are
digital" got written down and then used to pick the next year's work. It does not hold:
FY2024 carries its own text on page 53 and is a scan on the other ten pages that are
unfinished, and FY2020, FY2022 and FY2023 are mixed the same way. A report can be typeset
for most of its length and paste in a photographed section -- which is exactly what the
Treasurer's and payroll sections are in several years.

So the test is run per page, and the answer is a table rather than a sentence.

AND IT IS NOT WIRED INTO `check_generated.py`, deliberately. It opens every annual report,
some of them 78 MB, and takes minutes; the checks that run before a commit are the ones
that catch a defect, and a survey going stale is not a defect. Re-run it when the page
tracker moves.

WHAT `digital` MEANS HERE, EXACTLY

More than 40 words in the text layer of that page. A scanned page is not always zero -- a
stamped page number or a running header can be real text over a photograph -- so a bare
`any words at all` reports scans as digital. 40 is comfortably above the header-only case
and far below any table. It is a SCREEN, not a proof: a page can pass and still hold its
table as an image, which is what FY2025 page 115 does. The region has to be checked too,
and the process doc says so.
"""
import argparse
import collections
import csv
import glob
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGES = os.path.join(ROOT, 'sources', 'data', 'annual-report-pages.csv')
OUT = os.path.join(ROOT, 'notes', 'generated', 'TEXT-LAYER-COVERAGE.md')
MIN_WORDS = 40


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    import pdfplumber

    left = collections.defaultdict(list)
    for r in csv.DictReader(open(PAGES, encoding='utf-8')):
        if r['state'] != 'proven':
            left[r['fy']].append((int(r['page']), r['state']))

    pdfs = {}
    for f in glob.glob(os.path.join(ROOT, 'sources', 'town-annual-reports', 'docs',
                                    '*annual-town-report.pdf')):
        m = re.search(r'fy-(\d{4})-', f)
        if m:
            pdfs[m.group(1)] = f

    rows, missing = [], []
    for fy in sorted(left):
        if fy not in pdfs:
            missing.append(fy)
            continue
        dig = []
        with pdfplumber.open(pdfs[fy]) as doc:
            for page, _ in sorted(left[fy]):
                if page - 1 < len(doc.pages) and \
                        len(doc.pages[page - 1].extract_words()) > MIN_WORDS:
                    dig.append(page)
        rows.append((fy, len(left[fy]), dig))

    body = io.StringIO()
    w = body.write
    w('# Text-layer coverage of the unfinished annual-report pages\n\n')
    w('Generated by `scripts/survey_text_layer.py`. Do not edit.\n\n')
    w('A page counts as **digital** when its text layer holds more than %d words. That is a\n'
      'screen and not a proof: a page can pass and still keep its TABLE as an image, which\n'
      'is what FY2025 page 115 does, so the region has to be checked too. See\n'
      '`notes/process/READING-A-REPORT-PAGE.md`.\n\n' % MIN_WORDS)
    tot_left = sum(n for _, n, _ in rows)
    tot_dig = sum(len(d) for _, _, d in rows)
    w('**%d of %d unfinished pages carry their own text.** The rest are photographs, where\n'
      'recognition is the only reader and the work is slower per page.\n\n'
      % (tot_dig, tot_left))
    w('| year | left | digital | scanned | the digital pages |\n')
    w('|---|---:|---:|---:|---|\n')
    for fy, n, dig in sorted(rows, key=lambda r: (-len(r[2]), r[0])):
        shown = ', '.join(str(p) for p in dig[:16]) + (' …' if len(dig) > 16 else '')
        w('| FY%s | %d | %d | %d | %s |\n' % (fy, n, len(dig), n - len(dig), shown or '—'))
    w('| **total** | **%d** | **%d** | **%d** | |\n' % (tot_left, tot_dig, tot_left - tot_dig))
    if missing:
        w('\nNo PDF held for: %s.\n' % ', '.join('FY' + m for m in missing))
    w('\n## What this is for\n\n')
    w('It ranks the backlog by what it will COST rather than by how many pages are left.\n'
      'FY2024 has the fewest pages outstanding of any year and only one of them is digital;\n'
      'FY2014 has more and every one carries its text. Those are not the same job, and the\n'
      'page count alone cannot tell them apart.\n')
    text = body.getvalue()

    if a.check:
        cur = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        if cur != text:
            print('STALE %s -- run: python3 scripts/survey_text_layer.py'
                  % os.path.relpath(OUT, ROOT), file=sys.stderr)
            return 1
        print('ok -- %d of %d unfinished pages are digital' % (tot_dig, tot_left))
        return 0

    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write(text)
    print('wrote %s -- %d of %d unfinished pages are digital'
          % (os.path.relpath(OUT, ROOT), tot_dig, tot_left))
    return 0


if __name__ == '__main__':
    sys.exit(main())
